### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TianXiaSky** [moesnow/March7thAssistant#101]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.7.4

### 重现步骤

更新后无法锄地了，删除锄地的配置也没用，而且锄地模块更新也无法更新
![锄地异常](https://github.com/moesnow/March7thAssistant/assets/45476763/11ca5cda-5d76-44fc-829b-a23b685b8154)
![锄地无法更新](https://github.com/moesnow/March7thAssistant/assets/45476763/9b9f3ff8-9c62-4f06-86bc-a7c3207aa1e1)

### 期望的结果是什么？

正常锄地

### 实际的结果是什么？

无法锄地，无法更新

**Comment by moesnow** [comment]
手动更新锄地模块，链接在图中“开始下载”后面
