### ISSUE TITLE
[Bug]: 偶发：触发Windows导致开始菜单挡住游戏窗口导致无法识别

### ISSUE THREAD

**Issue by Heipen** [moesnow/March7thAssistant#111]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.7.5

### 重现步骤

在未打开游戏的情况下使用完整运行，在游戏登录完成进入游戏界面后脚本会自动触发Windows键打开开始菜单，挡住游戏界面导致无法识别，此时即使手动关闭开始菜单脚本也会再自动打开。

### 期望的结果是什么？

不要触发Windows键

### 实际的结果是什么？

打开开始菜单导致无法识别，进而无法正常运行

**Comment by moesnow** [comment]
没有自动按Windows键的功能，能提供`log`吗

**Comment by MusherM** [comment]
我偶尔也会出现这个情况，挂着人没动，第二天发现windwos菜单挂在那个地方

**Comment by MusherM** [comment]
> ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> * [x]  我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
> * [x]  我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
> * [x]  我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
> * [x]  我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
> 
> ### March7thAssistant 版本 （或 Commit Id）
> 1.7.5
> 
> ### 重现步骤
> 在未打开游戏的情况下使用完整运行，在游戏登录完成进入游戏界面后脚本会自动触发Windows键打开开始菜单，挡住游戏界面导致无法识别，此时即使手动关闭开始菜单脚本也会再自动打开。
> 
> ### 期望的结果是什么？
> 不要触发Windows键
> 
> ### 实际的结果是什么？
> 打开开始菜单导致无法识别，进而无法正常运行
> 
> ### 日志记录
> _No response_
> 
> ### 补充说明（可选）
> _No response_

我使用simpleRDP客户端的时候会有这种情况，换用mobaxterm后就没遇到过了，你可以试试
