### ISSUE TITLE
[Bug]: 不能识别外圈遗器【幽冥之径】（追击套+速度套）

### ISSUE THREAD

**Issue by yingxr** [moesnow/March7thAssistant#117]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.7.6

### 重现步骤

1. 设置：体力用于刷侵蚀隧洞（遗器），选择最新的副本【幽冥之径】（追击套+速度套）
2. UI界面点击清体力

### 期望的结果是什么？

1. 识别到该副本
2. 点击传送
3. 开始战斗

### 实际的结果是什么？

1. 识别不到该副本
2. 不断地向下滚动菜单
3. 重复第2步数次后报warning，不执行刷副本任务，并退出

### 补充说明（可选）

经测试，
设置体力用于刷侵蚀隧洞（遗器），最新的副本【幽冥之径】的上一个（生命套+速度套），
可以正常运行

**Comment by MusherM** [comment]
我也遇到这个问题了
[2024-01-27.log](https://github.com/moesnow/March7thAssistant/files/14070585/2024-01-27.log)

**Comment by moesnow** [comment]
尝试 [March7thAssistant v1.7.7.3](https://github.com/moesnow/March7thAssistant/releases/tag/v1.7.7.3)
