### ISSUE TITLE
[Bug]: failed to start in Windows Terminal

### ISSUE THREAD

**Issue by Lutra-Fs** [moesnow/March7thAssistant#12]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.5.1

### 重现步骤

打开在 Windows Terminal 执行。
报错。

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

[出现错误 2147942402 (0x80070002) (启动“"./March7th Assistant.exe" main”时)]

### 补充说明（可选）

error 2147942402 is a "File not Found" in Windows. So maybe the relative path were not resolved correctly?

**Comment by moesnow** [comment]
Actually, I'm not sure why this error is occurring.
Try opening Windows Terminal with administrator privileges.
Use the 'cd' command to navigate to the folder where 'March7thAssistant' is located.
Then, enter the following commands:
1. cmd
2. wt ./"March7th Assistant.exe" main

Does it run successfully?

**Comment by Lutra-Fs** [comment]
Nope

**Comment by Lutra-Fs** [comment]
![image](https://github.com/moesnow/March7thAssistant/assets/36790218/0edb97a9-16a5-419d-a5e4-35e2c481f72a)

**Comment by Lutra-Fs** [comment]
Dig further, I guess that is the problem https://github.com/microsoft/terminal/issues/15487 .

**Comment by Lutra-Fs** [comment]
Any chance to implement a workaround like using Windows Powershell to start the exe?

**Comment by moesnow** [comment]
I have changed it to an absolute path.
Please try this: https://github.com/moesnow/March7thAssistant/suites/16954149090/artifacts/968619495

**Comment by Lutra-Fs** [comment]
> I have changed it to an absolute path. Please try this: https://github.com/moesnow/March7thAssistant/suites/16954149090/artifacts/968619495

This one works well
