### ISSUE TITLE
[Feat]: 未来有可能增加自动标记词条较差的遗器的功能吗？

### ISSUE THREAD

**Issue by YunXi7370** [moesnow/March7thAssistant#127]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

1500的圣遗物上限还是有点糟心，咱用助手了就懒得亲自查看遗器，会出现一整理就头大，不整理没得刷的问题，现在推出了标记圣遗物的功能（锁定和废品两种），是否可以让三月七帮忙查看副词条，具体关于需要选择哪些词条的规则可以由玩家自行定义。仅推出筛选废品就已经万分感谢啦~

**Comment by YunXi7370** [comment]
<img width="326" alt="{0DE09B89-3C02-4cde-BAC5-575B67E9E8F7}" src="https://github.com/moesnow/March7thAssistant/assets/149073295/4a6fca91-377f-4f02-9b39-16e2aa7458c7">

**Comment by moesnow** [comment]
暂无计划
