### ISSUE TITLE
2.0版本无法跳过体力消耗

### ISSUE THREAD

**Issue by ddd-zero** [moesnow/March7thAssistant#130]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.0

### 重现步骤

1.6版本的时候，把选择消耗体力的项目改为空白名就可以跳过体力消耗，介绍中也是推荐这么操作的。2.0之后无法通过这种方法跳过体力消耗。希望能增加个开关，因为入坑晚，还没到养老阶段，想把每天的体力分配到不同的项目中，但这个功能不太好做，只能自己手动操作。但还是想让三月七执行一些重复的操作，诸如领助战/派遣，还有在凌晨4点运行比较耗时的锄大地

### 期望的结果是什么？

能跳过

### 实际的结果是什么？

2.0版本会直接出错终止

**Comment by moesnow** [comment]
补充截图或日志信息

**Comment by 0frostmourne0** [comment]
不能留空吧，指定项目写个“无”就跳过了。
