### ISSUE TITLE
[Feat]: 向onepush的custom增加更多接口

### ISSUE THREAD

**Issue by yhzcake** [moesnow/March7thAssistant#134]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

正在使用onebot协议的其他实现,希望添加:
1.增加参数datatype可选为json或data(默认data,期望为json)
2.增加可选参数配置custom是否支持发送image(默认为false,期望为true)
3.参数data中可以通过format将title,content,image(base64)替换进字符串中,

**Comment by moesnow** [comment]
无计划，欢迎PR
