### ISSUE TITLE
[Feat]: 希望恢复原有更新方式

### ISSUE THREAD

**Issue by CX330J** [moesnow/March7thAssistant#139]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

希望恢复原有程序内更新并自动覆盖的方式

**Comment by moesnow** [comment]
没看懂，现在不就是“程序内更新并自动覆盖”的方式吗？

**Comment by CX330J** [comment]
我这边是跳转到浏览器下载的，是我这边设置有问题吗

**Comment by moesnow** [comment]
方便给个录屏吗？

**Comment by CX330J** [comment]
https://github.com/moesnow/March7thAssistant/assets/146555752/3490318b-8fc5-4c04-8a1f-120b04d0380a

**Comment by moesnow** [comment]
试试删除软件路径中的 “（1）”

**Comment by CX330J** [comment]
感谢感谢，已解决

**Comment by moesnow** [comment]
47427aad9a78dd136ecccee24a2b2b1e37022cd5
