### ISSUE TITLE
[Bug]: 使用PushPlus作为推送时，仍因空白内容无法推送

### ISSUE THREAD

**Issue by BeatSeat** [moesnow/March7thAssistant#14]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v1.5.1

### 重现步骤

使用 PushPlus 作为推送方式，完整运行并使游戏正常结束。

### 期望的结果是什么？

在 PushPlus 中收到正常推送结果。

### 实际的结果是什么？

PushPlus 无法正常推送，但同时 win_notify 方式生成的通知正常。测试 PushPlus 的官方推送方式正常。

### 补充说明（可选）

通过查询 PushPlus 内部历史消息显示，该推送实际上内容（content）为空所以未能推送。

查询代码发现，实际上在 https://github.com/moesnow/March7thAssistant/commit/b269f6b4296a3eb35f2c9d508774eba9ff4007f5 处已经尝试进行修复，但该修复并不完全，我认为应改为：
```python
content = '.' if content is None or content == '' else content
```
因为下方 notify() 的默认值与实际使用Notify中给 content 赋值为空字符串而非 None

**Comment by moesnow** [comment]
6b7afd8c06ee8734a84e92608122d44dcfbc601a
