### ISSUE TITLE
[Feat]: 希望可以添加检测遗器是否满1500背包。防止导致无法打遗器本。

### ISSUE THREAD

**Issue by xunyoyo** [moesnow/March7thAssistant#140]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

已知一个问题：遗器满的时候是打不了遗器本的，然后就会导致每日实训无法完成。是否考虑检测这个东西然后选择自动4星及以下清理？

**Comment by moesnow** [comment]
fd1975aa61f66009ca2bc83963135d1bc0e8d98c
