### ISSUE TITLE
error 游戏分辨率304*201 请在游戏设置内切换为 1920+1080 窗口或全屏运行

### ISSUE THREAD

**Issue by ddd-zero** [moesnow/March7thAssistant#145]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.0.0.5

### 重现步骤

-

### 期望的结果是什么？

-

### 实际的结果是什么？

-

**Comment by ddd-zero** [comment]
不知道从哪个版本开始的，每次第一次完整运行都是正常。第二天程序凌晨4点自动运行就这样了。游戏已经打开了，分辨率也是正常1920×1080，游戏界面停留在 点击进入的界面。

以前的版本，完成运行后，连续几天都是正常的。



![image](https://github.com/moesnow/March7thAssistant/assets/57771987/fcd91252-e9de-405d-8fee-1975aea9dc8d)


![image](https://github.com/moesnow/March7thAssistant/assets/57771987/fa92a8ac-63b0-47e2-9a7b-da20c356beb8)

**Comment by moesnow** [comment]
从所给的信息里看不出什么问题导致的

**Comment by moesnow** [comment]
可以尝试一下最新版本，手动覆盖更新

**Comment by ddd-zero** [comment]
我测试了几次。可能是因为，我在自动化运行崩铁每日的这台电脑上，手动登陆打开过崩铁，然后那个登录器每次懒得关，好像就会出现这种情况。它总是切到那个登录器上？ 自从我关上登录器后，没有出现过这种情况了
