### ISSUE TITLE
[Bug]: 筑梦边境漏了个怪

### ISSUE THREAD

**Issue by VRmaple** [moesnow/March7thAssistant#146]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.0.1.6

### 重现步骤

![c4743b16f1c71fcbd2a1a9766d7c82f](https://github.com/moesnow/March7thAssistant/assets/148715376/859da076-5ad8-4352-915c-6373f59e3085)

### 期望的结果是什么？

修一下喵

### 实际的结果是什么？

一直漏了个怪

### 补充说明（可选）

谢谢喵

**Comment by moesnow** [comment]
请给锄地项目提 issue: https://github.com/linruowuyin/Fhoe-Rail
