### ISSUE TITLE
[Bug]: 更新未删除历史垃圾文件导致的锄大地4-3-1错乱的问题

### ISSUE THREAD

**Issue by Leapiny** [moesnow/March7thAssistant#147]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.0.1.6

### 重现步骤

在[v2.0.0.5](https://github.com/moesnow/March7thAssistant/releases/tag/v2.0.0.5)版本中，3rdparty\Fhoe-Rail\map\目录下的map_4-3_01.json文件名是01，02，03命名格式。
但是在[v2.0.1.6](https://github.com/moesnow/March7thAssistant/releases/tag/v2.0.1.6)版本中，3rdparty\Fhoe-Rail\map\目录下的map_4-3_1.json文件名是1，2，3命名格式。可能是升级逻辑是直接复制替换的关系，导致升级后的目录中同时存在4-3_01,4-3_02,4-3_03与与4-3_1,4-3_2,4-3_3两种重复的文件，最终导致程序异常。

### 期望的结果是什么？

升级后，3rdparty\Fhoe-Rail\map\目录中只保留最新的4-3_1,4-3_2,4-3_3......类文件，删除4-3_01,4-3_02.4-3_03........类文件

### 实际的结果是什么？

升级后，3rdparty\Fhoe-Rail\map\目录中只保留最新的4-3_1,4-3_2,4-3_3......类文件，与4-3_01,4-3_02.4-3_03........类文件 同时存在，导致程序异常。

**Comment by moesnow** [comment]
从旧版本升级上来请手动删除一下，`v2.0.1` 及后续版本在更新后都会正常删除原map文件夹。 85fe8d4e3da7f8eeb1fabc543911dd409b8d734c
