### ISSUE TITLE
[Feat]: 后备开拓力

### ISSUE THREAD

**Issue by CX330J** [moesnow/March7thAssistant#15]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

能否新增补充后备体力的操作
即当剩余体力在设定值的60%或左右，可以识别后备体力并补齐所需体力

**Comment by moesnow** [comment]
c32f7eec7a800e139d96fc484b41d69ac975835a
