### ISSUE TITLE
[Feat]: 希望能在软件内加入快捷查看日志的功能

### ISSUE THREAD

**Issue by NewbieXvwu** [moesnow/March7thAssistant#150]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

如题，希望能添加一个按钮，快捷查看日志。已搜索Issue（关键词“日志”），未发现重复Issue。麻烦开发者了，谢谢！
（我即将开学，可能回复会很慢，敬请谅解！）

**Comment by moesnow** [comment]
[March7thAssistant v2.0.6-beta2](https://github.com/moesnow/March7thAssistant/releases/tag/v2.0.6-beta2)
