### ISSUE TITLE
[Bug]: 启动游戏语句改变 + cannot access local variable 'value'

### ISSUE THREAD

**Issue by Eisaichen** [moesnow/March7thAssistant#155]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

 v2.0.2.3 7c57f60

### 重现步骤

1. 禁用自动分辨率修改修改
2. 启动游戏

### 期望的结果是什么？

不会报错，且能通过非exe启动游戏

### 实际的结果是什么？

cannot access local variable 'value' where it is not associated with a value

### 日志记录

<img width="602" alt="Screenshot 2024-02-24 180500" src="https://github.com/moesnow/March7thAssistant/assets/12467320/ef676889-6896-4457-a166-4d8ef41dfb96">

### 补充说明（可选）

报错是因为，禁用了自动分辨率修改后，start.py中的value变量没有赋值，进行至相关判断语句时就会报错

另一个问题是，过去用于启动游戏的语句是：
os.system(f"cmd /C start \"\" \"{config.game_path}\"")
而现在是：
subprocess.Popen(config.game_path, creationflags=subprocess.DETACHED_PROCESS)

前者可以调用所有cmd能直接运行的命令，也包括bat，而后者不行
即使将路径设置成下面的形式：
`game_path: '["C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe", "D:\Application\StarRail_Launcher\Start_Starrail_Hold_HDR.ps1"]' # 游戏路径`
也会因为`creationflags=subprocess.DETACHED_PROCESS`而无法正常执行，也无法通过前置的路径有效性检测`check_path`

希望可以保留一个能通过脚本启动的手段，谢谢
（我的游戏运行在VM中，所以需要通过bat运行来注入反-反作弊，否则原版游戏无法在VM中运行）

**Comment by moesnow** [comment]
aea2d56c3a68edbff715ab9c411b45d22a495045

**Comment by Eisaichen** [comment]
大佬神速，感谢❤️
