### ISSUE TITLE
March7thAssistant v2.0.3.4 Latest每周第一次锄地卡模拟宇宙[Bug]: 

### ISSUE THREAD

**Issue by jelly0925** [moesnow/March7thAssistant#158]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

March7thAssistant v2.0.3.4 Latest

### 重现步骤

每周第一次手动锄地的时候，脚本切换界面会卡在模拟宇宙

### 期望的结果是什么？

不应该卡在模拟宇宙地图界面

### 实际的结果是什么？

手动锄地可以设置为不打开模拟宇宙地图？

**Comment by moesnow** [comment]
锄地问题请反馈给 Fhoe-Rail 项目: https://github.com/linruowuyin/Fhoe-Rail
