### ISSUE TITLE
[Feat]: 支持任意界面断网重连

### ISSUE THREAD

**Issue by RiZhiZhaoYi** [moesnow/March7thAssistant#16]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

遇到突发性的短时间断网，希望能够每隔几十秒或几分钟点击一下重连

**Comment by moesnow** [comment]
4ee5367c58790b2391d28e01203df9443c533e07
