### ISSUE TITLE
[Bug]: 锄大地传送定位不准确导致卡死

### ISSUE THREAD

**Issue by fannntuan** [moesnow/March7thAssistant#163]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.0.4.3

### 重现步骤

在使用原版运行时 指定地图为梦境酒店
![IMG_0771](https://github.com/moesnow/March7thAssistant/assets/112638944/ab2b46d1-4152-442d-8f89-2b2588306cfa)
![IMG_0770](https://github.com/moesnow/March7thAssistant/assets/112638944/573ff255-adb2-4d39-935c-a44eb9156dd0)

### 期望的结果是什么？

定位到精确锚点并正常运行

### 实际的结果是什么？

出现传送错误然后一直等待的情况

### 补充说明（可选）

问题发现者目前登不上git所以由我代发

![IMG_0772](https://github.com/moesnow/March7thAssistant/assets/112638944/8876d03b-ba2a-45f0-8b6d-c5785a561a89)

问题发现者QQ号：252752190

**Comment by smjes3** [comment]
@fannntuan 已收到这个bug，正在准备修复中。

不过方便问下这个是首次锄地的时候出现的吗，目前实际测试是重跑的时候会出现这个问题。
