### ISSUE TITLE
[Bug]: 配置文件的输入没有错误，但软件界面点击完整启动就闪退

### ISSUE THREAD

**Issue by CykaZH** [moesnow/March7thAssistant#168]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.0.5

### 重现步骤

app界面点击完整启动、锄大地、清体力等任务时就闪退

### 期望的结果是什么？

成功运行脚本

### 实际的结果是什么？

脚本界面点击启动游戏可以启动，但点击完整启动、锄大地、清体力等任务时，command界面闪退，脚本界面消失，游戏未启动；

**Comment by moesnow** [comment]
看不出任何问题，请尝试重新下载。

**Comment by CykaZH** [comment]
> 看不出任何问题，请尝试重新下载。

重新下载后仍然出现该情况，但通过main.py启动能够正常运行自动化脚本，通过app.py界面启动自动化脚本也会闪退

**Comment by CykaZH** [comment]
> > 看不出任何问题，请尝试重新下载。
> 
> 重新下载后仍然出现该情况，但通过main.py启动能够正常运行自动化脚本，通过app.py界面启动自动化脚本也会闪退

报错如下
Traceback (most recent call last):
  File "D:\March7thAssistant\app\card\samplecardview1.py", line 94, in mouseReleaseEvent
    start_task(self.action)
  File "D:\March7thAssistant\tasks\base\tasks.py", line 19, in start_task
    subprocess.Popen(["wt", sys.executable, "main.py", command], creationflags=subprocess.DETACHED_PROCESS)
  File "D:\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by moesnow** [comment]
无法复现，可能你本地运行环境存在问题。
如果无法解决可以尝试打包后的集成版 [March7thAssistant v2.0.5](https://github.com/moesnow/March7thAssistant/releases/tag/v2.0.5)

**Comment by Eisaichen** [comment]
从日志里看，这个好像只是你游戏路径配置的问题，建议重新设置下游戏路径试试

**Comment by CykaZH** [comment]
> 从日志里看，这个好像只是你游戏路径配置的问题，建议重新设置下游戏路径试试

集成版也试过了
路径也从新设置过了，March7th Launcher的GUI界面点击后还是会闪退
而直接运行同目录下的March7th Assistant.exe文件可以正常执行在March7th Launcher.exe（config.yaml）中设置好的任务
算了 将就着用吧 : (

**Comment by moesnow** [comment]
> > 从日志里看，这个好像只是你游戏路径配置的问题，建议重新设置下游戏路径试试
> 
> 集成版也试过了 路径也从新设置过了，March7th Launcher的GUI界面点击后还是会闪退 而直接运行同目录下的March7th Assistant.exe文件可以正常执行在March7th Launcher.exe（config.yaml）中设置好的任务 算了 将就着用吧 : (

尝试一下，打开 Windows设置 - 应用 - 应用执行别名，然后关闭 终端（wt.ext） 的选项试试

**Comment by CykaZH** [comment]
> > > 从日志里看，这个好像只是你游戏路径配置的问题，建议重新设置下游戏路径试试
> > 
> > 
> > 集成版也试过了 路径也从新设置过了，March7th Launcher的GUI界面点击后还是会闪退 而直接运行同目录下的March7th Assistant.exe文件可以正常执行在March7th Launcher.exe（config.yaml）中设置好的任务 算了 将就着用吧 : (
> 
> 尝试一下，打开 Windows设置 - 应用 - 应用执行别名，然后关闭 终端（wt.exe） 的选项试试

感谢，确实有用
