### ISSUE TITLE
[Feat]: 希望新增闪退自动登录功能

### ISSUE THREAD

**Issue by cjwjy007** [moesnow/March7thAssistant#169]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

锄大地/模拟宇宙时经常触发奇怪的闪退问题。（3台电脑都这样）
报错日志是unity的lib问题，
d3d11.dll caused an Access Violation (0xc0000005)
  in module d3d11.dll at 0033:2550c6e0.
估计是星穹铁道自身优化问题。

希望在配置中新增一个按钮，开启后在一个线程中定时检测游戏是否存活，若未检测到游戏窗口则启动并切换到前台。（我试过这样做的话锄大地和模拟宇宙的脚本都会自动继续运行）

**Comment by moesnow** [comment]
暂无计划，建议将画质改到最低，30帧也是可以正常跑的
