### ISSUE TITLE
[Feat]: 增加WEBUI 优化远程控制和全屏看不到日志输出

### ISSUE THREAD

**Issue by LoSiTeE** [moesnow/March7thAssistant#17]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

增加webui并为其开放可以自定义的ui端口，这样远程控制脚本能更加方便。

**Comment by QiE2035** [comment]
一种基于 PyWebIO 的非侵入式简易实现，仅提供运行停止和查看部分日志输出的功能，修改配置请使用原 GUI（在远程外部修改也可生效）
该实现非常糟糕，存在各种bug，仍有极大的进步空间。ALAS 可能是一种优秀参考 ~~（还请避免使用 Electron）~~
另一种可能的简易非侵入实现方式是基于 NiceGUI，或者侵入式的使用 FastAPI 等 API 接口融入原 GUI

源代码：[web.zip](https://github.com/moesnow/March7thAssistant/files/13467057/web.zip)

~~事实上如果只是需要看日志可输出的话不妨试试看日志文件？~~
~~要控制运行停止不妨试试 SSH ？~~
