### ISSUE TITLE
建议在在锄大地任务前后各执行一次委托任务

### ISSUE THREAD

**Issue by smallmj** [moesnow/March7thAssistant#171]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

设定的每天凌晨4点自动执行，如果做的是20个小时的委托，凌晨4点领取，需要前一天早上8点开始委托任务。然而，8点的时候一般锄大地还在进行，等到可以手动设定委托的时候，一般已经9点以后，导致第二天的自动领取委托任务依旧无法按时进行。
建议将委托任务设定在锄大地之后进行或者在前后各执行一遍委托任务。

**Comment by smallmj** [comment]
可以调整为每天4点和9点各执行一次

**Comment by Leapiny** [comment]
有类似需求：
1、平时本来每天都是锄大地后领取，大约9点多。
2、但是到了周一，因为要模拟宇宙，导致领取会在晚上19，20领取。 这样会导致第二天开始，锄大地后9点多领取不到。我每次都是周二开始手工领取2次，追上进度，到了周四、五开始，每天9点多锄大地后又能领取到。但到了下周一又是一个循环。
3、也希望能把委托领取的时间，可以配置在锄大地前领取一次。因为这个时间是相对固定的。不会受到锄大地、模拟宇宙这些长时间运行任务的影响。

**Comment by moesnow** [comment]
尝试 [March7thAssistant v2.0.6-beta1](https://github.com/moesnow/March7thAssistant/releases/tag/v2.0.6-beta1)
