### ISSUE TITLE
[Feat]: 关于模拟宇宙积分奖励

### ISSUE THREAD

**Issue by cangXuann** [moesnow/March7thAssistant#172]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

1.注意到脚本每周第一次运行模拟宇宙时，识别不出自动出现的积分奖励页面，就卡在那了。
2.也希望能加入积分奖励的自动领取功能
3.不知为什么，经常在设置每周只运行两次模拟宇宙的情况下，第二天在开启模拟宇宙的情况下完整运行，它还是会自动多跑模拟宇宙，或许可以基于积分奖励的检测进行次数检测

**Comment by moesnow** [comment]
1.多等一会，有异常处理会自动关闭的
2.一直都有
3.请检查“模拟宇宙上次完成时间”的配置项是否修改成功，如果第一天任务失败是不会记录的。

**Comment by cangXuann** [comment]
> 1.多等一会，有异常处理会自动关闭的 2.一直都有 3.请检查“模拟宇宙上次完成时间”的配置项是否修改成功，如果第一天任务失败是不会记录的。

明白了，不好意思打扰了
