### ISSUE TITLE
[Feat]: 关于查看（确认）第三方项目版本时的易用性改进

### ISSUE THREAD

**Issue by saki3525** [moesnow/March7thAssistant#173]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

最近锄大地项目 [Fhoe-Rail]的更新较为频繁。
所以我每次打开3月7助手时我都要进入第三方的Fhoe-Rail文件夹里打开version.txt确认版本和github上Fhoe-Rail进行比对。
以上操作较为繁琐。所以提出以下关于确认第三方项目版本时的易用性改进：

实现方法1
为version.txt的文件名重命名为version-0.00.0.txt（此处0为版本号）
这样的话就不用每次打开txt来确认版本。

实现方法2
直接在3月7的GUI中的现有第三方项目按钮附近处显示版本相关信息，（如果能自动查询原项目的版本信息并加以表示则更好）

因为我是编程小白，所以猜测方法2的实现也许较为麻烦。
至于是否实现此项功能则交给项目主判断了。

**Comment by moesnow** [comment]
暂无计划
