### ISSUE TITLE
[Bug]: 更换手机壁纸导致"指南"相似度过低

### ISSUE THREAD

**Issue by steamaaaaaaaaaa** [moesnow/March7thAssistant#18]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.60

### 重现步骤

无名勋礼会隔一段时间下架，在下架的时候指南按钮会因为勋礼消失而变换位置，程序无法识别

### 期望的结果是什么？

大大可否改进一下

### 实际的结果是什么？

谢谢

### 日志记录

[2023-10-09_23-56-56.log](https://github.com/moesnow/March7thAssistant/files/12848286/2023-10-09_23-56-56.log)

**Comment by steamaaaaaaaaaa** [comment]
![Uploading 屏幕截图 2023-10-10 001029.png…]()

**Comment by steamaaaaaaaaaa** [comment]
![之前的](https://github.com/moesnow/March7thAssistant/assets/145114918/b1ae1909-3a00-4ef8-8c45-e7cb1ebb8a36)
![屏幕截图 2023-10-10 001029](https://github.com/moesnow/March7thAssistant/assets/145114918/60988247-13df-4947-8a4c-f2cb9ad364fc)

**Comment by moesnow** [comment]
这个问题是更换手机壁纸导致的相似度过低，试试切换回默认壁纸

**Comment by moesnow** [comment]
41b7d39074c19fc134623f1e1abbb01fecc5438f

现在会自动切换回默认壁纸
