### ISSUE TITLE
[Bug]: Python 版本 3.9 不允许将联合类型编写为 X | Y 导致无法正常使用

### ISSUE THREAD

**Issue by jilliss** [moesnow/March7thAssistant#182]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

ddfa1197

### 重现步骤

py版本：Python 3.9.13
pip版本：pip 24.0 from March7thAssistant\venv\lib\site-packages\pip (python 3.9)
命令行启动`python ./app.py`  后，点击锄大地 notification.py文件报错

### 期望的结果是什么？

理论上正常运行

### 实际的结果是什么？

PyCharm 中，显示 Python 版本 3.9 不允许将联合类型编写为 X | Y
需要将`notification`文件中`_process_image`和`notify`方法的参数
 `Optional[io.BytesIO | str | Image.Image]`  改为 `Optional[Union[io.BytesIO, str, Image.Image]]`

**Comment by moesnow** [comment]
请升级到 Python 3.11.X

**Comment by jhll1124** [comment]
据我使用3.9是兼容性最好的版本，更新会导致其他脚本无法正常运行

**Comment by moesnow** [comment]
> 据我使用3.9是兼容性最好的版本，更新会导致其他脚本无法正常运行

可以多个Python版本共存的，然后使用虚拟环境（venv）
