### ISSUE TITLE
[Bug]: 在1920*1200的屏幕下启动完整运行，会将已经设为1920*1080窗口化的屏幕，设为1920*1080全屏幕，导致程序运行错误

### ISSUE THREAD

**Issue by 0xingchen0** [moesnow/March7thAssistant#183]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.0.5.6

### 重现步骤

1.启动gui的完整运行或March7th Assistant.exe；
2.游戏以全屏模式启动；
3.程序报错退出；
4.手动开启游戏发现分辨率被修改；
5.关闭自动修改分辨率依然会出现该问题

### 期望的结果是什么？

程序正常进入完整运行流程

### 实际的结果是什么？

程序报错退出

**Comment by moesnow** [comment]
下个版本修复，但是关闭自动修改分辨率应该是有效的
