### ISSUE TITLE
[Bug]: 更新1.6后按键及点击坐标错误

### ISSUE THREAD

**Issue by yhzcake** [moesnow/March7thAssistant#19]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.6.0

### 重现步骤

执行完整运行

### 期望的结果是什么？

正确打开队伍配置及每日实训

### 实际的结果是什么？

打开队伍配置按下了T(改按键之后会正常)
打开每日实训在错误的地方进行了鼠标点击(578, 211)

### 日志记录

[2023-10-09_10-02-42.log](https://github.com/moesnow/March7thAssistant/files/12855411/2023-10-09_10-02-42.log)

### 补充说明（可选）

最好是将这些按键或点击坐标建议一个新的文件(例如json)进行配置,这样还可以让用户自行适配界面分辨率

**Comment by moesnow** [comment]
鼠标点击的坐标不是固定写死的，是通过图像对比自动获取的。

无法切换到 `星际和平指南-每日实训` 的原因是金人巷壁纸导致的相似度过低，在你的log中可见相似度小于 `0.95` 。
`目标图片：./assets/images/screen/guide/enter_guide.png 相似度：0.9475843906402588`

目前最简单的办法是切换到默认壁纸即可，队伍配置的按键以后会添加配置选项，默认为 `T`

**Comment by moesnow** [comment]
https://github.com/moesnow/March7thAssistant/issues/18
