### ISSUE TITLE
[Feat]: 能否新增过期邮包购买和艾迪恩代币购买的选项

### ISSUE THREAD

**Issue by vvincee7** [moesnow/March7thAssistant#193]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

好像是一周刷新一次

**Comment by htshts1115** [comment]
foerail已经有该功能

**Comment by vvincee7** [comment]
了解，不过还是想看看三月七这边能不能增添功能

**Comment by niuhuan** [comment]
稍后我会开发一下， 思路类似选择命途

**Comment by niuhuan** [comment]
#238
