### ISSUE TITLE
[Bug]: 启用github镜像后更新出现错误

### ISSUE THREAD

**Issue by Georgebillion** [moesnow/March7thAssistant#2]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.3.4

### 重现步骤

1.打开软件
2.检查github镜像选项是否不留空
3.打开设置-检查更新，复现报错

### 期望的结果是什么？

正常更新无报错

### 实际的结果是什么？

弹出检查更新报错提示框

### 日志记录

切换debug模式后无日志输出，故截图参考

### 补充说明（可选）

![image](https://github.com/moesnow/March7thAssistant/assets/40432824/856e5ab8-eb58-404f-a24e-1d31e9352932)
![image](https://github.com/moesnow/March7thAssistant/assets/40432824/1b290786-9b1d-4c60-9b6b-188e8a6c6d65)
![image](https://github.com/moesnow/March7thAssistant/assets/40432824/b7d790e2-d72e-49f0-9dd2-a6fa4029f618)

**Comment by moesnow** [comment]
检测更新不会使用Github镜像，只有在下载时候会用到。
从最后一张图的底部可以看出请求的确实是`api.github.com`这个域名，报错信息显示的是本地证书存在问题导致SSL错误。

**Comment by Georgebillion** [comment]
怪了，我用的watt toolkits 3.0版本，证书已经重新安装过一次了，但还是不行。还是能复现

> 检测更新不会使用Github镜像，只有在下载时候会用到。 从最后一张图的底部可以看出请求的确实是`api.github.com`这个域名，报错信息显示的是本地证书存在问题导致SSL错误。

**Comment by moesnow** [comment]
新发布的 v1.3.5 中，新增了一个选项用于开关证书验证，可以尝试改为 false

`verify_ssl: true #启用 SSL 证书验证`
