### ISSUE TITLE
[Feat]: 关于手柄模式使用自动对话的优化

### ISSUE THREAD

**Issue by fannntuan** [moesnow/March7thAssistant#208]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

基于崩铁现在已经支持手柄键鼠热切换了，但是自动对话还是无法识别到手柄模式已经开启对话，建议加入一个手柄模式进入对话的图像监听，当监听到图片后可以模拟点击一下键盘或者模拟移动一下鼠标使其切换到键鼠模式再进行对话。
![Star Rail 2024_3_29 14_46_34](https://github.com/moesnow/March7thAssistant/assets/112638944/d19ce36e-6a10-4600-ad64-a22628635b28)

**Comment by Inoristory** [comment]
对，我刚想反馈
