### ISSUE TITLE
[Feat]: 希望可以加入死亡自动复活

### ISSUE THREAD

**Issue by xunyoyo** [moesnow/March7thAssistant#209]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

![image](https://github.com/moesnow/March7thAssistant/assets/33387866/396f0dd2-54b6-45d3-972b-c324eef7a6cb)
希望可以死亡检测，然后可以传送到信标回血，然后再重新打，因为不知道为什么问题突然就暴毙了

**Comment by niuhuan** [comment]
锄大地的功能？应该提到这里 https://github.com/linruowuyin/Fhoe-Rail

我想的是，死了之后需要从上个传送点重新继续播放脚本。或许可行。
