### ISSUE TITLE
[Bug]: 锄大地 一直不动

### ISSUE THREAD

**Issue by rosebudgrave** [moesnow/March7thAssistant#213]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

最新版本

### 重现步骤

1.远程登陆星穹 全屏 1920*1080
2.打开小助手启用锄大地
然后就一直在黑塔空间站站着不动

### 期望的结果是什么？

可以正常锄大地

### 实际的结果是什么？

在黑塔空间站动不了

### 日志记录

![image](https://github.com/moesnow/March7thAssistant/assets/45752666/d184ef11-a37f-48b6-8c87-99702088c754)

### 补充说明（可选）

用的多用户远程登录,分辨率全屏 1920*1080,使用本地用户可以正常锄大地

**Comment by jowilksasella** [comment]
**雖然這是fhoe-rail的問題，你要到那邊的項目投issue，而不是這邊，但我還是解答一下你的問題。**
你可以試試登出用戶後重開SimpleRemote
或者不要最大化SimpleRemote(因為這會導致它出現白邊，可能影響了偵測)
