### ISSUE TITLE
[Feat]: 希望加入启动后自动运行，运行完成后运行指定程序的功能

### ISSUE THREAD

**Issue by 2023899320** [moesnow/March7thAssistant#214]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

这样我电脑可以自动开机自动刷自动关机，谢谢

**Comment by 0frostmourne0** [comment]
刷完关机这个功能本身就有，再设置—程序里可以修改。

不过这个功能也算是有一定的需求，比如可以让多账号之间的衔接更丝滑一些。

**Comment by Eisaichen** [comment]
用Windows内置的计划任务就能实现开机自动运行了，记得勾选最高权限运行
<img width="605" alt="Screenshot 2024-06-01 023145" src="https://github.com/moesnow/March7thAssistant/assets/12467320/9e271218-62d5-4bb7-bcee-926a2885b122">
运行`March7th Assistant.exe`就会自动执行完整运行
(`March7th Assistant.exe`不是`March7th Launcher.exe`)

同时三月七本身也支持完成后关机
<img width="508" alt="image" src="https://github.com/moesnow/March7thAssistant/assets/12467320/d4abee0a-5ac1-4b4b-945f-0368d3098342">
