### ISSUE TITLE
[Feat]: 希望支持繁體文本 

### ISSUE THREAD

**Issue by TimLam1** [moesnow/March7thAssistant#217]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

希望支持繁體文本

**Comment by mmmjie** [comment]
并非开发者，从路人的角度发表意见

这个工作量不小
而会繁中的看简中应该也没阅读障碍，直接把游戏语言改简体？
