### ISSUE TITLE
[Feat]: 能否添加“手动确认完成当日某项任务”，如锄大地、模拟宇宙等

### ISSUE THREAD

**Issue by BROWNBRONY** [moesnow/March7thAssistant#230]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

因各种原因（包括但不限于：网络波动、页面杂乱、游戏临时更新、程序页面长时间卡住不动）导致某项任务（如锄大地、模拟宇宙）当日未能判定完成，在三月七小助手24小时循环运行的情况下会导致第二天（凌晨4点）无法继续循环运行。因此能否添加手动确认某项任务当日已完成，当日再运行小助手时可以跳过该项任务以保证第二天可以顺利循环运行。

**Comment by 0frostmourne0** [comment]
“上次运行时间”里改成当天不就好了吗……
