### ISSUE TITLE
[Bug]: 新版材料合成页面会被卡住，建议添加每日跳过合成的选项

### ISSUE THREAD

**Issue by BROWNBRONY** [moesnow/March7thAssistant#231]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.1.1.1

### 重现步骤

完整运行-材料合成

### 期望的结果是什么？

优化合成逻辑，添加跳过选项

### 实际的结果是什么？

画面卡主不动

**Comment by WhiteBlock114514** [comment]
我也遇到了这个问题，目前是2.3.0版本，这里上传我遇到这个问题的日志
[2024-07-01.log](https://github.com/user-attachments/files/16050930/2024-07-01.log)

**Comment by moesnow** [comment]
5d774ce05cceab25add3a4795d23990a894ae7ef
