### ISSUE TITLE
[Bug]: 抽卡记录 功能不支持国际服

### ISSUE THREAD

**Issue by mmmjie** [moesnow/March7thAssistant#249]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.1.1.1以及2.2.0

### 重现步骤

打开游戏查看游戏内的抽卡记录，在确认距离上次抽卡过了1个小时后
打开本项目插件，点击"抽卡记录“功能的更新数据

### 期望的结果是什么？

正确获取抽卡记录

### 实际的结果是什么？

提示抽卡记录为空

### 日志记录

![Uploading QQ截图20240508221405.png…]()

**Comment by mmmjie** [comment]
![QQ截图20240508221405](https://github.com/moesnow/March7thAssistant/assets/45615222/507a8b44-b1b7-4442-9f60-b1ddd41b532a)

**Comment by moesnow** [comment]
尝试删除根目录下的 `warp.json` ，再更新数据试试。
这边没有国际服测试环境，更新前有国际服用户试过应该是能正常获取的。

**Comment by mmmjie** [comment]
> 尝试删除根目录下的 `warp.json` ，再更新数据试试。 这边没有国际服测试环境，更新前有国际服用户试过应该是能正常获取的。

试了还是一样，我看了一下warp.json文件内容，是有正常下载下来的

但程序UI上就是显示记录为空，不显示

这是我删除后，重新更新抽卡记录后生成的文件

[warp.json](https://github.com/moesnow/March7thAssistant/files/15258462/warp.json)

**Comment by moesnow** [comment]
2714d7f79575927f0e38529048ed624bf5945b27

稍后尝试升级 [March7thAssistant v2.2.0.2](https://github.com/moesnow/March7thAssistant/releases/tag/v2.2.0.2) ，应该修复了

**Comment by mmmjie** [comment]
> [2714d7f](https://github.com/moesnow/March7thAssistant/commit/2714d7f79575927f0e38529048ed624bf5945b27)
> 
> 稍后尝试升级 [March7thAssistant v2.2.0.2](https://github.com/moesnow/March7thAssistant/releases/tag/v2.2.0.2) ，应该修复了

已解决，感谢
