### ISSUE TITLE
[Bug]: 委托功能异常，无法执行一键委托

### ISSUE THREAD

**Issue by lxl605695683** [moesnow/March7thAssistant#250]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

V2.1.1.1

### 重现步骤

启动March7thAssistant-点击设置-点击日常分页-勾选“领取委托奖励”
进入游戏-点击完整运行-游戏界面卡在委托界面上不再操作，脚本经过多次重试后自动结束

### 期望的结果是什么？

能正常领取委托奖励并不再影响后续的脚本操作

### 实际的结果是什么？

脚本卡在委托界面，不再操作；
脚本重试两次后自动结束脚本运行

### 日志记录

+-------------------------------------------------------------------------------------------------------------------+
|                                                   开始检测更新                                                    |
+-------------------------------------------------------------------------------------------------------------------+
2024-05-09 10:43:49,252 | INFO | 已经是最新版本：v2.1.1.1
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                     开始运行                                                      |
+-------------------------------------------------------------------------------------------------------------------+
2024-05-09 10:43:49,333 | INFO | 游戏启动：F:\Star Rail\Game\StarRail.exe
2024-05-09 10:43:59,336 | INFO | 游戏窗口已切换到前台
2024-05-09 10:44:30,711 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
------------------------------------------------------- 完成 --------------------------------------------------------
+-------------------------------------------------------------------------------------------------------------------+
|                                                 开始领取委托奖励                                                  |
+-------------------------------------------------------------------------------------------------------------------+
2024-05-09 10:44:34,887 | INFO | 当前界面：主界面
2024-05-09 10:44:36,662 | INFO | 切换到：手机菜单
================================================== 检测到委托奖励 ===================================================
2024-05-09 10:44:37,412 | INFO | 当前界面：手机菜单
2024-05-09 10:44:50,100 | WARNING | 切换到 委托 超时，准备重试
2024-05-09 10:44:51,499 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-05-09 10:44:55,475 | INFO | 当前界面：手机菜单
2024-05-09 10:45:08,135 | WARNING | 切换到 委托 超时，准备重试
2024-05-09 10:45:09,496 | WARNING | 未识别出任何界面，请确保游戏画面干净，按ESC后重试
2024-05-09 10:45:13,435 | INFO | 当前界面：手机菜单
2024-05-09 10:45:26,053 | ERROR | 无法切换到 委托
2024-05-09 10:45:26,061 | ERROR | 请确保游戏画面干净，关闭帧率监控HUD、网速监控等一切可能影响游戏界面截图的组件
2024-05-09 10:45:26,061 | ERROR | 如果是多显示器，游戏需要放在主显示器运行，且不支持HDR或游戏滤镜
2024-05-09 10:45:26,062 | ERROR | 发生错误 无法切换到指定游戏界面
2024-05-09 10:45:26,075 | INFO | winotify 通知发送完成

### 补充说明（可选）

疑似游戏内“一键领取委托奖励”按钮的尺寸变小，导致一键领取的时候脚本无法正确识别画面，从而引发委托操作失败终止脚本。

辛苦作者大大排查一下是否是这个问题，因为如果没有委托奖励的时候，脚本还是可以正常运行的。

感恩kira(<ゝω·)~☆

**Comment by dConstantineb** [comment]
![dispatch](https://github.com/moesnow/March7thAssistant/assets/87115639/3fbb21ba-5bc4-45b0-bbe2-eb85f21ffc95)
把这张图替换掉%\March7thAssistant_v2.0.2.3\assets\images\screen\dispatch.png就能解决

**Comment by moesnow** [comment]
f15b9ea2d9136f6e4b45eccab2e31b4d8c794d9a

**Comment by lxl605695683** [comment]
了解了，非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月9日(周四) 下午3:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [moesnow/March7thAssistant] [Bug]: 委托功能异常，无法执行一键委托 (Issue #250)




 
dispatch.png (view on web)
 把这张图替换掉%\March7thAssistant_v2.0.2.3\assets\images\screen\dispatch.png就能解决
