### ISSUE TITLE
[Bug]: 自动 HDR 相关问题

### ISSUE THREAD

**Issue by AxionnG** [moesnow/March7thAssistant#253]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.2.0.3

### 重现步骤

使用M7A启动星穹铁道并进行自动战斗，关闭后，使用官方启动器启动星穹铁道，自动HDR失效（设置中开启，但在星穹铁道中无法触发）

### 期望的结果是什么？

使用M7A启动星穹铁道时自动HDR禁用；但使用官方启动器时自动HDR可正常触发（未使用M7A前，自动HDR在星穹铁道上可触发）

### 实际的结果是什么？

使用M7A启动星穹铁道时自动HDR禁用；但使用**官方启动器**时自动HDR**仍无法正常触发**，现象包括画面对比度低、无自动HDR触发提示、截图无过曝现象等。

**Comment by moesnow** [comment]
请检查 `设置 → 游戏 → 游戏模式 → 显示卡`，是否勾选了 `不使用 Auto HDR`。

将日志等级修改为详细后，启动时会输出具体的自动HDR开关日志，例如
```
2024-05-15 17:12:27,352 | DEBUG | 修改游戏自动 HDR: 启用 --> 禁用
2024-05-15 17:12:47,391 | DEBUG | 恢复游戏自动 HDR: 启用
```
注意如果在恢复设置项之前就关闭了程序，就不会自动恢复了

**Comment by AxionnG** [comment]
先前排查时已确定设置项中自动HDR开启，同时已确定game bar中自动HDR已开启；但实际无HDR效果，游戏启动时不弹出自动HDR通知，且game bar中调节自动HDR强度无效。
