### ISSUE TITLE
[Bug]: 锄大地存在部分地图的怪物没有覆盖

### ISSUE THREAD

**Issue by BROWNBRONY** [moesnow/March7thAssistant#255]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.2.0.3

### 重现步骤

如附件图片所示
默认使用远程角色1号位，跑图模式default，直接完整运行锄大地后的几乎必定漏怪情况：
1.朝露公馆走廊：1只
2.白日梦酒店左下和底部区域：6+只（如左下地图的2只电视机、底部地图右侧的4只怪）
3.收容舱段：1只

### 期望的结果是什么？

局部优化锄大地地图运行逻辑，消除几乎必定漏怪的情况

### 实际的结果是什么？

几乎必定漏怪情况：
1.朝露公馆走廊：1只
2.白日梦酒店左下和底部区域：数只（如左下地图的2只电视机、底部地图右侧的4只怪）
3.收容舱段：1只

### 日志记录

待补充

**Comment by BROWNBRONY** [comment]
![Uploading 白日梦酒店左下和底部区域.jpg…]()

**Comment by BROWNBRONY** [comment]
![白日梦酒店左下和底部区域](https://github.com/moesnow/March7thAssistant/assets/147940901/242be0d9-50b7-4c47-bddf-06ed9df7c0ad)
![朝露公馆走廊](https://github.com/moesnow/March7thAssistant/assets/147940901/db0a2ba6-4067-49b2-975f-b1d985be4e5e)
![收容舱段](https://github.com/moesnow/March7thAssistant/assets/147940901/edf2fa47-f871-43af-8460-90d2fc252e4e)

**Comment by moesnow** [comment]
锄地相关的问题麻烦反馈给 https://github.com/linruowuyin/Fhoe-Rail 项目
辛苦再发一次了
