### ISSUE TITLE
[Bug]: 忘却之庭不能使用男主

### ISSUE THREAD

**Issue by Forever-Yf** [moesnow/March7thAssistant#26]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.6.2_full

### 重现步骤

选择男主后自动退出

### 期望的结果是什么？

期望结果是能够正常运行

### 实际的结果是什么？

实际是脚本自动停止

**Comment by moesnow** [comment]
因为缺少男主两个命途的头像图片，方便的话麻烦在忘却之庭的界面，用小助手设置中的捕获截图功能，点击保存完整图片后，用未压缩的方式传上来，比如压缩包。

**Comment by Forever-Yf** [comment]
![CaelumPreservation](https://github.com/moesnow/March7thAssistant/assets/98394507/b7804f81-7fa0-4952-b0db-5c3747ce2b41)
存护男主CaelumPreservation

![CaelumDestruction](https://github.com/moesnow/March7thAssistant/assets/98394507/3f9e28e7-743f-4490-9ea2-309a596aae55)
毁灭男主CaelumDestruction

> 因为缺少男主两个命途的头像图片，方便的话麻烦在忘却之庭的界面，用小助手设置中的捕获截图功能，点击保存完整图片后，用未压缩的方式传上来，比如压缩包。

**Comment by Forever-Yf** [comment]
![CaelumPreservation](https://github.com/moesnow/March7thAssistant/assets/98394507/b7804f81-7fa0-4952-b0db-5c3747ce2b41)
存护男主CaelumPreservation

![CaelumDestruction](https://github.com/moesnow/March7thAssistant/assets/98394507/3f9e28e7-743f-4490-9ea2-309a596aae55)
毁灭男主CaelumDestruction

> 因为缺少男主两个命途的头像图片，方便的话麻烦在忘却之庭的界面，用小助手设置中的捕获截图功能，点击保存完整图片后，用未压缩的方式传上来，比如压缩包。

**Comment by moesnow** [comment]
> ![CaelumPreservation](https://user-images.githubusercontent.com/98394507/276863014-b7804f81-7fa0-4952-b0db-5c3747ce2b41.png) 存护男主CaelumPreservation
> 
> ![CaelumDestruction](https://user-images.githubusercontent.com/98394507/276863040-3f9e28e7-743f-4490-9ea2-309a596aae55.png) 毁灭男主CaelumDestruction
> 
> > 因为缺少男主两个命途的头像图片，方便的话麻烦在忘却之庭的界面，用小助手设置中的捕获截图功能，点击保存完整图片后，用未压缩的方式传上来，比如压缩包。

你这两张图是从 StarRailCopilot 那边拿的吧，模拟器和PC端分辨率不同不能通用的

**Comment by Forever-Yf** [comment]
> > ![CaelumPreservation](https://user-images.githubusercontent.com/98394507/276863014-b7804f81-7fa0-4952-b0db-5c3747ce2b41.png) 存护男主CaelumPreservation
> > ![CaelumDestruction](https://user-images.githubusercontent.com/98394507/276863040-3f9e28e7-743f-4490-9ea2-309a596aae55.png) 毁灭男主CaelumDestruction
> > > 因为缺少男主两个命途的头像图片，方便的话麻烦在忘却之庭的界面，用小助手设置中的捕获截图功能，点击保存完整图片后，用未压缩的方式传上来，比如压缩包。
> 
> 你这两张图是从 StarRailCopilot 那边拿的吧，模拟器和PC端分辨率不同不能通用的
[screenshots.zip](https://github.com/moesnow/March7thAssistant/files/13054599/screenshots.zip)
您看这样可以吗
