### ISSUE TITLE
[Feat]: 希望能增加一个打回忆和忘却之庭的时候会可以自动切换上下队伍的功能

### ISSUE THREAD

**Issue by lc41900957** [moesnow/March7thAssistant#260]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

在打忘却或者混沌回忆的时候有时候这一关属性克制是对应的，下一关属性克制都不对应了，希望能自动在作战失败后尝试交换上下队作战，或者作战成功后没有满星就交换一次上下队伍配置尝试作战，或者哪怕提供一键手动交换上下队伍配置功能，也能方便很多，每次在长长的名单里面找人真的有点头大

**Comment by moesnow** [comment]
> 自动在作战失败后尝试交换上下队作战

有这个功能
