### ISSUE TITLE
[Bug]: B服相关问题

### ISSUE THREAD

**Issue by yanabcd** [moesnow/March7thAssistant#261]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

最新

### 重现步骤

第一次安装了官方安装包，然后运行了脚本一键运行，发现不是这个客户端；
第二次安装了b站安装包，自己运行了游戏，然后用其他没问题，但是一键启动会跑到官方安装包的登录界面

### 期望的结果是什么？

一键运行正常运行b站客户端

### 实际的结果是什么？

一键运行启动客户端为官方客户端

**Comment by yanabcd** [comment]
![image](https://github.com/moesnow/March7thAssistant/assets/48935623/7eddad6c-befc-444c-b4bd-c24b0179c51c)
从脚本里进入就是这样，我自己手动进入就是
![image](https://github.com/moesnow/March7thAssistant/assets/48935623/b9526aea-ea95-433a-a979-a1da377310d4)
不知道为啥，有大佬懂吗，是注册表问题，还是缓存问题？

**Comment by yanabcd** [comment]
补充，启动目录都是相同的

**Comment by yanabcd** [comment]
> 设置里可以手动指定客户端路径

客户端路径我用的都一样，不知道为什么打开就不一样..

**Comment by moesnow** [comment]
B服就是这样的，参考 #33

**Comment by Eisaichen** [comment]
你可以新建一个bat文件，比如`launcher.bat`
里面内容如下
```
set GamePath=D:\Star Rail\Game

start "" /d "%GamePath%" "%GamePath%\StarRail.exe"
@exit
```
把第一行的路径改成你星铁的游戏目录
之后在三月七里把启动路径设置成这个bat即可

@moesnow B服似乎是因为启动exe的时候没有传递启动目录，所以读不到同目录下的config.ini
或许可以稍微改一下start.py解决
```
start.py
Ln 98

        logger.debug(_("运行命令: cmd /C start \"\" \"{path}\"").format(path=config.game_path))
+       game_folder = config.game_path.rpartition('\\')[0]
+       if os.system(f"cmd /C start \"\" /D \"{game_folder}\" \"{config.game_path}\""):
            return False
```
