### ISSUE TITLE
[Bug]: 導出當前帳戶導致閃退

### ISSUE THREAD

**Issue by seriaati** [moesnow/March7thAssistant#266]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.2.0.3

### 重现步骤

1. 打開 March7th Assistant
2. 點擊「帳戶」
3. 點擊「導出當前遊戲帳戶」

### 期望的结果是什么？

功能可以正常使用

### 实际的结果是什么？

程序崩潰

**Comment by Eisaichen** [comment]
非大陆服务器吧？

**Comment by seriaati** [comment]
是
