### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lujie2464** [moesnow/March7thAssistant#267]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.2.0.3

### 重现步骤

“锄大地”原版运行，设置“黄泉专用”。锄大地锄到凌晨四点时，弹出的月卡领取星琼界面。

### 期望的结果是什么？

能够在凌晨4点自动领取月卡，然后继续执行锄大地

### 实际的结果是什么？

锄大地进程被卡住了。只有当人手动点击领取星琼后，锄大地才会继续。

**Comment by Eisaichen** [comment]
这个实际上是负责锄大地的App的问题，可以到这里反馈：
https://github.com/linruowuyin/Fhoe-Rail/issues

见[三月七子模块](https://github.com/moesnow/March7thAssistant?tab=readme-ov-file#%E7%9B%B8%E5%85%B3%E9%A1%B9%E7%9B%AE)
