### ISSUE TITLE
[Bug]: 处于城市沙盘（凝滞虚影-嗔怒之形附近）时无法识别地图

### ISSUE THREAD

**Issue by UnusWhite** [moesnow/March7thAssistant#278]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.2.0.3

### 重现步骤

将所刷副本选为嗔怒之形或手动传送至城市沙盘中后进行完整运行

### 期望的结果是什么？

成功识别地图界面并进行下一步

### 实际的结果是什么？

报错并终止或无限重试

**Comment by htshts1115** [comment]
我也遇到了

**Comment by yanziandjay** [comment]
#257 已知問題了
