### ISSUE TITLE
[Feat]: 关于2.3版本更新的拆分宇宙

### ISSUE THREAD

**Issue by yhzcake** [moesnow/March7thAssistant#279]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

新拆分宇宙刷遗器更方便一些,而且可以避免第9宇宙无法读地图的问题

**Comment by Shotazt** [comment]
隔壁模拟宇宙大佬已经新建文件夹正在做了，这个三月七作者做的是整合

**Comment by yhzcake** [comment]
我倒是觉得这个跟那个模拟宇宙差距有点大，我更觉得跟本体相性比较好

**Comment by Shotazt** [comment]
没办法，开发旧宇宙的作者已宣布停止维修，现在已经新建文件夹在搞差分宇宙

**Comment by yhzcake** [comment]
坏，今天的自动模拟宇宙炸了，手册跳转第一页拆分宇宙不认识（

**Comment by yhzcake** [comment]
拆分更了,但应该有问题,至少还没发布
另:对于位面提取,希望在每日任务里添加检测有沉浸器的情况自动执行位面提取
并且最好能设置每周一是否运行位面提取任务,防止没有存档

**Comment by Shotazt** [comment]
> 作者差分宇宙有沒有放github上？找不到相關資訊。

因为作者是在QQ群里招聘的人，我是其中之一，不过只负责简单的整理工作

**Comment by htshts1115** [comment]
差分宇宙已经更新并且正常运行了。但现在3月7用的是old 分支，不是最新的分支。需要更新，并且适配新版代码

**Comment by Pythagoras-Euler** [comment]
现在三月七模拟宇宙可以切到新分支了吗？我这边怎么更新都是旧分支。直接下新分支的包替换进去能行吗？

**Comment by htshts1115** [comment]
要自己去模拟宇宙的项目拉最新的代码覆盖到三月七目录里

**Comment by Shotazt** [comment]
> 要自己去模拟宇宙的项目拉最新的代码覆盖到三月七目录里

不行的，我刚刚在邮箱收到信息发送了，不知道你们收到了没有，我再发一次，作者还没写适配差分宇宙的，所以不能去拉新分支

**Comment by Shotazt** [comment]
> 现在三月七模拟宇宙可以切到新分支了吗？我这边怎么更新都是旧分支。直接下新分支的包替换进去能行吗？

我刚刚在邮箱收到信息并回复了，不知道你们收到没有，我在GitHub在发一次，你看看我回复下一个人的

**Comment by htshts1115** [comment]
> > 要自己去模拟宇宙的项目拉最新的代码覆盖到三月七目录里
> 
> 不行的，我刚刚在邮箱收到信息发送了，不知道你们收到了没有，我再发一次，作者还没写适配差分宇宙的，所以不能去拉新分支

我都已经用过刷满了……  https://github.com/CHNZYX/Auto_Simulated_Universe  首页的说明都已经换了：此页面主要介绍差分宇宙自动化，如需详细的普通模拟宇宙自动化介绍请移步[普通宇宙](https://github.com/CHNZYX/Auto_Simulated_Universe/blob/old/README.md)

**Comment by Shotazt** [comment]
> > > 要自己去模拟宇宙的项目拉最新的代码覆盖到三月七目录里
> > 
> > 不行的，我刚刚在邮箱收到信息发送了，不知道你们收到了没有，我再发一次，作者还没写适配差分宇宙的，所以不能去拉新分支
> 
> 我都已经用过刷满了……  https://github.com/CHNZYX/Auto_Simulated_Universe  首页的说明都已经换了：此页面主要介绍差分宇宙自动化，如需详细的普通模拟宇宙自动化介绍请移步[普通宇宙](https://github.com/CHNZYX/Auto_Simulated_Universe/blob/old/README.md)

你说的没错，但是我所说的是三月七并不支持启动差分宇宙，二者并没有什么矛盾点，而刚刚那个人的意思明显是想要三月七能打差分宇宙，一般单独下载ZYX大佬的差分宇宙出现版本混乱会减少很多，这个差分宇宙项目我参与了一点点小工作（数据整理＋测试反馈）（注：并不是我一个人完成的）

**Comment by Pythagoras-Euler** [comment]
> > > > 要自己去模拟宇宙的项目拉最新的代码覆盖到三月七目录里
> > > 
> > > 
> > > 不行的，我刚刚在邮箱收到信息发送了，不知道你们收到了没有，我再发一次，作者还没写适配差分宇宙的，所以不能去拉新分支
> > 
> > 
> > 我都已经用过刷满了……  https://github.com/CHNZYX/Auto_Simulated_Universe  首页的说明都已经换了：此页面主要介绍差分宇宙自动化，如需详细的普通模拟宇宙自动化介绍请移步[普通宇宙](https://github.com/CHNZYX/Auto_Simulated_Universe/blob/old/README.md)
> 
> 你说的没错，但是我所说的是三月七并不支持启动差分宇宙，二者并没有什么矛盾点，而刚刚那个人的意思明显是想要三月七能打差分宇宙，一般单独下载ZYX大佬的差分宇宙出现版本混乱会减少很多，这个差分宇宙项目我参与了一点点小工作（数据整理＋测试反馈）（注：并不是我一个人完成的）

所以说想用自动差分宇宙的话需要拉取分支后单独启动，没法覆盖到三月七的对应目录下进行一键启动对吧

**Comment by Shotazt** [comment]
> > > > > 要自己去模拟宇宙的项目拉最新的代码覆盖到三月七目录里
> > > > 
> > > > 
> > > > 不行的，我刚刚在邮箱收到信息发送了，不知道你们收到了没有，我再发一次，作者还没写适配差分宇宙的，所以不能去拉新分支
> > > 
> > > 
> > > 我都已经用过刷满了……  https://github.com/CHNZYX/Auto_Simulated_Universe  首页的说明都已经换了：此页面主要介绍差分宇宙自动化，如需详细的普通模拟宇宙自动化介绍请移步[普通宇宙](https://github.com/CHNZYX/Auto_Simulated_Universe/blob/old/README.md)
> > 
> > 你说的没错，但是我所说的是三月七并不支持启动差分宇宙，二者并没有什么矛盾点，而刚刚那个人的意思明显是想要三月七能打差分宇宙，一般单独下载ZYX大佬的差分宇宙出现版本混乱会减少很多，这个差分宇宙项目我参与了一点点小工作（数据整理＋测试反馈）（注：并不是我一个人完成的）
> 
> 所以说想用自动差分宇宙的话需要拉取分支后单独启动，没法覆盖到三月七的对应目录下进行一键启动对吧

没错

**Comment by moesnow** [comment]
c42305ad6b6eeca0f6b89626ed4a0eb96ed10e10
