### ISSUE TITLE
[Feat]: 优化 gocqhttp 的请求方式

### ISSUE THREAD

**Issue by chenkid999** [moesnow/March7thAssistant#28]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

目前 gocqhttp 推送的方式是使用 get 请求，但是由于图片的加入，使得请求链接变的巨长，希望能够优化为 post 请求，并将所有参数传入请求体内进行发送

**Comment by moesnow** [comment]
见 https://github.com/Mrs4s/go-cqhttp/issues/2471 优化已经没意义了，qqbot 相关的项目这几天不是归档停更，就是被请喝茶删库跑路
