### ISSUE TITLE
[Bug]: 模拟宇宙失败会卡住，既不退出也不重新挑战

### ISSUE THREAD

**Issue by wangxunshi** [moesnow/March7thAssistant#289]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.3.0

### 重现步骤

在模拟宇宙中挑战失败

### 期望的结果是什么？

能够重新挑战或者直接退出

### 实际的结果是什么？

卡在失败界面无反应

### 日志记录

无

### 补充说明（可选）

无

**Comment by i-cecreamer** [comment]
去模拟宇宙分支下最新版单独运行，这个作者还没适配呢

**Comment by SuperSB** [comment]
模拟宇宙走路是真的蠢，进图不直接向前走，必须是转个视角往后走
