### ISSUE TITLE
[Feat]: 支援不需要优先级

### ISSUE THREAD

**Issue by niuhuan** [moesnow/March7thAssistant#292]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

最近发现每日没有自动完成（好友太少了，没有指定的支援角色）
我比较懒，不想去看好友都有啥，希望配置里加一个选项，随便拉来一个队友用来做每日就行了

**Comment by ljxun** [comment]
本来就是没有优先级的会自动吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月8日(周一) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [moesnow/March7thAssistant] [Feat]: 支援不需要优先级 (Issue #292)




 
请确保您已阅读以上注意事项，并勾选下方的确认框。
  
 我确定这是一个从未被提出和实现过的功能。
 
 我已经在 Issue Tracker 以及 Pull Request 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
 
 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
 
 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
  
需要添加的功能内容
 
最近发现每日没有自动完成（好友太少了，没有指定的支援角色）
 我比较懒，不想去看好友都有啥，希望配置里加一个选项，随便拉来一个队友用来做每日就行了

**Comment by niuhuan** [comment]
不知道为什么，锄大地历时8个小时。按理说这个应该完成了

![b87265d1393846d01aa88127a164691a](https://github.com/moesnow/March7thAssistant/assets/20847533/b0744c61-f5fc-42ba-a48b-f8ee1b34bda6)

![930c50b1bb5f85169b0191e17061f4e5](https://github.com/moesnow/March7thAssistant/assets/20847533/f397f1c9-29e7-4364-8074-b266b899c21f)

**Comment by yunshaochu** [comment]
锄大地用的都是你自己的角色，和支援没关系

**Comment by niuhuan** [comment]
> 锄大地用的都是你自己的角色，和支援没关系

完整运行->清体力->锄大地（恢复了80体力）->清体力（支援）。大概就是这个意思
