### ISSUE TITLE
[Feat]: 希望加入差分宇宙 和  开机自启动

### ISSUE THREAD

**Issue by ycyeen** [moesnow/March7thAssistant#298]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

希望加入差分宇宙 似乎你们适配的模拟宇宙项目已更新差分宇宙 我诚恳希望加入差分宇宙

希望加入开机自启动并进行完整运行

**Comment by Shotazt** [comment]
开机自动动用Windows自带的任务计划就可以解决

**Comment by ycyeen** [comment]
> 开机自启动用Windows自带的任务计划就可以解决

Windows自带的任务计划不行，或者说 启动有大概率不响应不启动 而且似乎无法完成  “希望加入开机自启动并进行完整运行‘’ 的完整运行。

**Comment by 123hi123** [comment]
我用的就是 Windows 自帶的那個，你要打開完整權限

**Comment by niuhuan** [comment]
> 开机自启动用Windows自带的任务计划就可以解决

即便用Windows开机自启动可以解决，但是我个人认为仍然需要完善APP，增加适用场景，增加自动启动选项在设置面板。

**Comment by zzc-tongji** [comment]
我这里有个方案。

你需要有一个[米家智能插座](https://www.mi.com/shop/buy/detail?product_id=16421)，设置：
   - 每天定时3:45通电。
   - 若功率小于10W，则自动断电。

修改电脑的BIOS为通电开机，不同的主板方式不同，自己搜下。

如果你的电脑有开机密码，则用 [Autologon](https://learn.microsoft.com/en-us/sysinternals/downloads/autologon) 自动输入密码登陆。这个是微软官方提供的，可以放心使用。

打开**计划任务（计算机管理/系统工具/计划任务程序）**，导入下列配置。这个配置会在每天4点运行三月七小助手CLI工具。

``` xml
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2024-09-21T16:11:16.1089979</Date>
    <URI>\March7thAssistant</URI>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>2024-09-22T04:00:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay>
        <DaysInterval>1</DaysInterval>
      </ScheduleByDay>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-3024063896-2563758441-1971039008-1001</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>3</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>"你自己的路径\March7th Assistant.exe"</Command>
    </Exec>
  </Actions>
</Task>
```

在三月七小助手GUI工具里面，将 **设置/程序/任务完成后** 设为 **关机**。

这样就可以开机运行关机一条龙了。

**Comment by moesnow** [comment]
937b1b56c80db9e7f3e70b4902041e2771e37f93
