### ISSUE TITLE
[Feat]: 允许使用anaconda作为python解释器

### ISSUE THREAD

**Issue by wryx166** [moesnow/March7thAssistant#30]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

直接用conda的python在模拟宇宙会抛出一些问题，比如scripts未被正常调用

看上去至少有两处调用了python：
一处是gui调用的python，这个问题未知，因为我手动激活了conda环境
另一处是模拟宇宙的（由于启动模拟宇宙时通过新建command启动，没有继承gui的环境）要修改的地方为tasks/weekly/universe.py的71行附近，添加"conda activate env"

**Comment by moesnow** [comment]
conda 应该是可以用的，尝试修改 `config.yaml` 中的 `python_exe_path`。
可以参考 https://github.com/moesnow/March7thAssistant/issues/24#issuecomment-1772344948

**Comment by wryx166** [comment]
> conda 应该是可以用的，尝试修改 `config.yaml` 中的 `python_exe_path`。 可以参考 [#24 (comment)](https://github.com/moesnow/March7thAssistant/issues/24#issuecomment-1772344948)

我确实是直接修改 config.yaml 中的python_exe_path以调用conda的python.exe
这样可以正常使用并通过首次gui的环境检测，但是在模拟宇宙Auto_Simulated_Universe首次运行时找不到opencv等包，触发二次下载。
估计大部分人图的就是开箱即用，这个功能实现的必要性也不大。
