### ISSUE TITLE
[Bug]: 客户端的帮助-“远程本地多用户桌面”超链接点击没有反应

### ISSUE THREAD

**Issue by SheldonHoo233** [moesnow/March7thAssistant#306]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.3.0

### 重现步骤

在客户端上点击帮助-“远程本地多用户桌面”超链接。

### 期望的结果是什么？

跳转网页，或弹窗提示教程。

### 实际的结果是什么？

点击后无法跳转网页。

### 补充说明（可选）

可能的解决方法是assets/docs/Tutorial.md第11行的地址更正为https://github.com/moesnow/March7thAssistant/blob/ee3ea05286de51c9f347b200da1b37fac2fdad3f/assets/docs/Background.md

**Comment by 123hi123** [comment]
远程本地多用户桌面”超链接点击没有反应
這個超鏈接是什麼？
我也用了一段時間的遠程，本地多桌面，然後用的也是呃作者的教程。然後呃目前用盤也沒有遇到什麼大問題
頂多就是偶爾儀器都滿的，沒有辦法刷而已

**Comment by SheldonHoo233** [comment]
> 远程本地多用户桌面”超链接点击没有反应 這個超鏈接是什麼？ 我也用了一段時間的遠程，本地多桌面，然後用的也是呃作者的教程。然後呃目前用盤也沒有遇到什麼大問題 頂多就是偶爾儀器都滿的，沒有辦法刷而已

![image](https://github.com/user-attachments/assets/9708ec19-5c41-43f1-9b3a-cc862aea3813)
![image](https://github.com/user-attachments/assets/c6b4d0cc-8656-4200-80e9-f61111b64861)
嗯，我的意思是，如果作为一位不知道如何开启远程本地多用户桌面的玩家，似乎是无法通过点击电脑客户端的超链接，跳转到github的页面的，也就不一定能看到教程。（但不敢确定是否是我个人环境问题）只是看不到教程，不影响软件主要功能的使用。

**Comment by 123hi123** [comment]
教程我記得在github裏 你可以留issue的話，你應該是可以找得到
他是一個B站的連結，所以照理來說應該不管台灣中國都可以
