### ISSUE TITLE
[Bug]: 无法识别佩拉角色头像

### ISSUE THREAD

**Issue by FangLiangSheng** [moesnow/March7thAssistant#314]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

V2.3.0

### 重现步骤

启动忘却之庭和虚构叙事开关，点击主页的完整运行。忘却之庭和虚构叙事的队伍配置：1、黄泉（秘技/开怪）。2、花火（秘技一次）。3、佩拉（误操作）。4、符玄（秘技1次）

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

无法识别佩拉的角色头像，导致在选择人物界面时，任务就提前结束，脚本终止。

**Comment by moesnow** [comment]
最好能把日志一起发上来，这边测试佩拉是没问题的
```
2024-08-31 09:35:17,823 | DEBUG | 目标图片：share/character/Pela.png 相似度：0.97
2024-08-31 09:35:17,933 | DEBUG | 鼠标点击 (364, 681)
```
