### ISSUE TITLE
[Feat]: 逐光捡金：椒丘、翡翠

### ISSUE THREAD

**Issue by momlucky** [moesnow/March7thAssistant#319]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

[new_charater.zip](https://github.com/user-attachments/files/16851834/new_charater.zip)

**Comment by 13167755816** [comment]
这个我还没测试能不能用，因为现在的号已经手动打满了，只是截了图

**Comment by moesnow** [comment]
0540556e7a41da68cc313ba374e6764f8f09360b
