### ISSUE TITLE
[Feat]: 日常清体力支持模拟宇宙 && 遗器自动截图和通知推送

### ISSUE THREAD

**Issue by zihuanfeng520** [moesnow/March7thAssistant#32]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

想要模擬宇宙能自動使用體力，我看好像只有沉浸器可以換遺器，還有希望能創建一個資料夾，讓腳本自動截圖新獲得的五星遺器的屬性，不然刷完還要去背包找出新的儀器，然後希望在此基礎上，增加能鎖定特殊主/副詞條的功能，希望不會太複雜 再次感謝大佬的工具

**Comment by moesnow** [comment]
已支持修改模拟宇宙运行频率 61c03ce27e53eae53b82c4fd70bacc7728566848
