### ISSUE TITLE
[Bug]: ”饰品提取“中，”强制使用支援角色“选项不生效

### ISSUE THREAD

**Issue by Loshepherd** [moesnow/March7thAssistant#323]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.4.0

### 重现步骤

1. ”体力-副本类型“设置为”饰品提取“
2. ”支援-强制使用支援角色“开关开启
3. 运行”清体力“

### 期望的结果是什么？

借用好友支援角色完成”饰品提取“关卡

### 实际的结果是什么？

在不使用支援角色的情况下执行”饰品提取“
<details>

<summary>运行截图与设置截图</summary>

![屏幕截图 2024-09-05 171506](https://github.com/user-attachments/assets/d4b1fc39-78ad-4fc1-80e1-8f46c74b9c07)

![屏幕截图 2024-09-05 171248](https://github.com/user-attachments/assets/13c55ab0-f71f-431f-a49e-0cf88541fdbc)

![屏幕截图 2024-09-05 171236](https://github.com/user-attachments/assets/cb89683e-7889-49d5-9bd1-532f8b39f9fa)

</details>

**Comment by moesnow** [comment]
6c78e94ce09cc0b00a6c2530d652e34a1531bea7
