### ISSUE TITLE
[Bug]: 差分宇宙不能配队，也不是大世界队伍。系统单独配了一个角色就进去了。

### ISSUE THREAD

**Issue by ZuoAn-007** [moesnow/March7thAssistant#324]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.4.0

### 重现步骤

直接执行差分宇宙

### 期望的结果是什么？

使用大世界队伍，或系统中配对

### 实际的结果是什么？

系统配了一个人物就直接进入差分宇宙

### 日志记录

INFO [2024-09-05 20:32:32,586] [admin.py:29] isUserAdmin - CheckTokenMembership returned: True
INFO [2024-09-05 20:32:32,586] [diver.py:985] debug: False
WARNING [2024-09-05 20:32:32,922] [utils.py:106] 等待游戏窗口
INFO [2024-09-05 20:32:32,922] [utils.py:142] DPI: 1.0 A:1.0
INFO [2024-09-05 20:32:32,922] [utils.py:145] TEXT: 崩坏：星穹铁道
INFO [2024-09-05 20:32:33,976] [utils.py:35] 通知：初始计数：1  开始运行
INFO [2024-09-05 20:32:34,404] [diver.py:174] 触发 加载界面:开始游戏
INFO [2024-09-05 20:32:34,404] [diver.py:141] 点击 开始游戏:[1523, 1635, 938, 971]
INFO [2024-09-05 20:32:35,999] [diver.py:174] 触发 模式选择:模式选择
INFO [2024-09-05 20:32:36,001] [diver.py:141] 点击 继续进度:[531, 631, 464, 493]
INFO [2024-09-05 20:32:36,406] [diver.py:141] 点击 常规演算:[531, 673, 220, 258]
INFO [2024-09-05 20:32:41,140] [log.py:54] area_text:  deep: 0
INFO [2024-09-05 20:32:41,862] [log.py:54] area_text: 113第一位面区域战斗 deep: 0
INFO [2024-09-05 20:32:41,863] [log.py:54] team_member: {'花火': 0}
INFO [2024-09-05 20:32:42,025] [diver.py:174] 触发 差分宇宙中:位面
INFO [2024-09-05 20:32:42,251] [log.py:54] area_text: 113第一位面区域战斗 deep: 0
INFO [2024-09-05 20:32:42,976] [log.py:54] area_text: 113第一位面区域战斗 deep: 0
INFO [2024-09-05 20:32:44,717] [log.py:54] floor: 1 state: 0 area: 战斗 text: 113第一位面区域战斗
INFO [2024-09-05 20:32:52,276] [diver.py:174] 触发 探索结束-失败:返回主界面
INFO [2024-09-05 20:32:52,277] [diver.py:141] 点击 返回主界面:[889, 1013, 958, 987]
INFO [2024-09-05 20:32:52,866] [diver.py:174] 触发 探索结束-失败:返回主界面
INFO [2024-09-05 20:32:52,866] [diver.py:141] 点击 返回主界面:[889, 1013, 940, 968]
INFO [2024-09-05 20:32:54,625] [diver.py:174] 触发 加载界面:开始游戏
INFO [2024-09-05 20:32:54,625] [diver.py:141] 点击 开始游戏:[1509, 1621, 938, 971]
INFO [2024-09-05 20:32:56,198] [diver.py:174] 触发 模式选择:模式选择
INFO [2024-09-05 20:32:56,198] [diver.py:141] 点击 常规演算:[529, 673, 297, 333]
INFO [2024-09-05 20:32:57,295] [diver.py:174] 触发 启动[差分宇宙]:启动
INFO [2024-09-05 20:32:58,201] [diver.py:141] 点击 启动:[1603, 1789, 945, 976]
WARNING [2024-09-05 20:33:02,443] [diver.py:85] 等待游戏窗口，当前窗口：搜索
INFO [2024-09-05 20:33:04,249] [diver.py:174] 触发 方程选择:方程
INFO [2024-09-05 20:33:04,250] [log.py:54] [{'raw_text': '惑世蠢役05G03孢子上限提高角色的终结技攻击使孢子爆裂后对攻击目标造成1次终结技伤害爆裂的孢子越多该伤害越高繁育智识', 'box': [261, 701, 450, 850], 'score': 8}, {'raw_text': '无神论者0503Q敌方目标承受的持续伤害状态类型越多角色对其造成的反震伤害越高存护虚无', 'box': [732, 1172, 450, 850], 'score': -2}, {'raw_text': '记忆医生0404角色施放攻击后珠露会对冻结状态下的敌方目标额外造成1次伤害冻结状态下的敌方目标越多伤害越高记忆丰饶', 'box': [1202, 1642, 450, 850], 'score': -2}]
INFO [2024-09-05 20:33:06,250] [diver.py:174] 触发 祝福选择:祝福
INFO [2024-09-05 20:33:06,250] [log.py:54] [{'raw_text': '智识之路获得5个随机祝福其中包含13个智识祝福开拓', 'box': [254, 694, 450, 850], 'score': 2}, {'raw_text': '丰饶之路获得5个随机祝福其中包含13个丰饶祝福开拓', 'box': [732, 1172, 450, 850], 'score': -3}, {'raw_text': '欢愉之路获得5个随机祝福其中包含13个欢愉祝福开拓', 'box': [1209, 1649, 450, 850], 'score': -3}]
INFO [2024-09-05 20:33:08,416] [diver.py:174] 触发 点击空白处关闭:空白
INFO [2024-09-05 20:33:08,416] [diver.py:141] 点击 点击空白:[864, 1039, 995, 1026]
INFO [2024-09-05 20:33:10,073] [diver.py:174] 触发 点击空白处关闭:空白
INFO [2024-09-05 20:33:10,073] [diver.py:141] 点击 点击空白:[864, 1039, 977, 1010]
WARNING [2024-09-05 20:33:11,480] [diver.py:85] 等待游戏窗口，当前窗口：D:\Software\March7thAssistant_v2.3.0_full\March7th Assistant.exe

**Comment by moesnow** [comment]
自己先配好队伍进入差分宇宙一次，然后退出，
游戏会自动保存队伍。
