### ISSUE TITLE
[Feat]: 希望提供自主启动B服的支持

### ISSUE THREAD

**Issue by SamsaranLRH** [moesnow/March7thAssistant#33]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

我只下载了B服且确保正确配置了游戏路径，在命令行中显示启动游戏时，它会打开官服，而我手动点击exe也是B服，这就导致我只能手动先进游戏再运行，运行完之后会退出游戏，命令行还在（设置的循环），第二天做每日的功能就会因为打开了官服而上不对号，希望能得到改进，谢谢

**Comment by MusherM** [comment]
能否提供b服的StarRail.exe的路径，里面基本的路径结构跟官服一样吗？
还有我不是很理解，你只下载了b服，为什么启动游戏还能启动官服？

**Comment by yang1261** [comment]
我官服b服都下载了，我也遇到了相同的情况，不过我将Star Rail\launcher.exe 替换掉就可以进入b服了
