### ISSUE TITLE
[Feat]: 能否在三月七助手里添加一个自动兑换兑换码的功能

### ISSUE THREAD

**Issue by Canda15** [moesnow/March7thAssistant#334]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

大概功能就是。你把兑换码一行行排好（最好能自动去除每个兑换码后面有可能带有的空格），放三月七里，等到三月七下一次运行程序做每日的时候，会自动把这些兑换码给兑换了。并且返回给推送每个兑换码是否兑换成功。

领一些媒体平台的星琼时，前面总会带点蚊子腿的兑换码。兑换非常费时间，每个兑换码直接还得间隔一定的时间，否则会说你兑换操作频繁。细节能加个这个功能

**Comment by moesnow** [comment]
466e4bd3a6ece4e8daa39dc294b33780bd6d208f
