### ISSUE TITLE
[Bug]: b服务在自动更新后会自动识别到官服的路径，希望可以给b服务器添加自动识别b服务器的功能，官服的游戏路径是Star Rail\Game\StarRail.exe而b服务器的游戏路径是Star Rail Game\StarRail.exe

### ISSUE THREAD

**Issue by woTMrinidaye** [moesnow/March7thAssistant#335]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.5.3

### 重现步骤

自动更新后b服务器会自动识别官方服务器的游戏路径

### 期望的结果是什么？

b服务器自动更新后可以自动识别b服务器的游戏路径

### 实际的结果是什么？

自动更新后b服务器会自动识别官方服务器的游戏路径

**Comment by moesnow** [comment]
没看懂，为什么B服更新后游戏路径会改变呢？
没变化应该不会自动修改的。
