### ISSUE TITLE
[Bug]: 在程序选项设置了正确的游戏路径，但不管点击主页的哪一个选项都无法启动，弹出的终端界面显示的提示是[出现错误 2147942402 (0x80070002) (启动“"{前路径}\March7thAssistant_v2.5.3_full\March7th Assistant.exe" main”时)]也就是软件安装路径，但点击启动游戏却可以正常启动

### ISSUE THREAD

**Issue by chenwen-jie** [moesnow/March7thAssistant#339]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.5.3

### 重现步骤

在程序选项设置了正确的游戏路径，但不管点击主页的哪一个选项都无法启动，弹出的终端界面显示的提示是[出现错误 2147942402 (0x80070002) (启动“"{前路径}\March7thAssistant_v2.5.3_full\March7th Assistant.exe" main”时)]也就是软件安装路径，但点击启动游戏却可以正常启动

### 期望的结果是什么？

正常运行挂机清体力

### 实际的结果是什么？

不管点击主页的哪一个选项都无法启动，弹出的终端界面显示的提示是[出现错误 2147942402 (0x80070002) (启动“"{前路径}\March7thAssistant_v2.5.3_full\March7th Assistant.exe" main”时)]也就是软件安装路径

**Comment by moesnow** [comment]
清检查杀毒软件，将`小助手文件夹`加入杀毒软件排除项

Windows Defender：`病毒和威胁防护` → `管理设置` → `添加或删除排除项`
