### ISSUE TITLE
[Feat]:  希望新增模拟宇宙的难度选择。

### ISSUE THREAD

**Issue by D9Lose** [moesnow/March7thAssistant#34]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

希望增加一个模拟宇宙的难度选择，当前脚本会强制选择最高难度的刷，但是我并没有解锁，也刷不过。
而只是往上的次级难度的话，已经解锁，且可以稳定打通。
如果是强制最高难度的运行的话，实际上该功能的门槛很高，那些练度不是很高，又迫切希望刷材料的人就用不了一点。

**Comment by moesnow** [comment]
使用前请先看教程
