### ISSUE TITLE
[Bug]: 通知配置覆盖问题

### ISSUE THREAD

**Issue by zzc-tongji** [moesnow/March7thAssistant#341]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.5.3

### 重现步骤

首先，直接用文本编辑器修改 `config.yaml` 中的 `飞书通知配置`，然后保存。

然后，在 `March7th Launcher.exe` 的窗口里面修改任何一个设置。

### 期望的结果是什么？

用文本编辑器修改的 `config.yaml` 中的 `飞书通知配置` 保持不变。

### 实际的结果是什么？

用文本编辑器修改的 `config.yaml` 中的 `飞书通知配置` 被**覆盖为默认值**。

### 补充说明（可选）

这么做的原因是，推送通知的设置无法在 `March7th Launcher.exe` 中完成，只能用文本编辑器完成。

解决方案（二选一）：

1. 在 `March7th Launcher.exe` 中加入修改推送通知配置的 UI。**这样可以避免用户自行改动配置文件。**
2. 在 `March7th Launcher.exe` 的修改配置，按照 `读入配置 - 修改对应项 - 写回配置` 来执行。**这样可以确保 GUI 和文本编辑的配置不发生冲突。**

**Comment by zzc-tongji** [comment]
我又试了下，修改 config 文件后，重新启动 `March7th Launcher.exe`，可以避免配置覆盖问题。

建议加入 wiki 。

**Comment by devil233-ui** [comment]
> 我又试了下，修改 config 文件后，重新启动 `March7th Launcher.exe`，可以避免配置覆盖问题。
> 
> 建议加入 wiki 。

我试了下目前的onebot是支持热重载的，飞书不太清楚
