### ISSUE TITLE
[Bug]: 提取位面饰品蠹役饥肠发生错误

### ISSUE THREAD

**Issue by Rabbiteese** [moesnow/March7thAssistant#342]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.5.3

### 重现步骤

关闭差分宇宙每日循环，打开备用体力，关闭优先合成沉浸器，体力界面打开位面饰品提取，其他每日任务照常开启。定时运行或者直接启动一条龙。

### 期望的结果是什么？

完成每日任务，刷取位面饰品

### 实际的结果是什么？

每日任务全部完成，体力一点没动，位面饰品刷取失败。在位面饰品的界面下拉寻找，找不到我要的副本。实际上蠹役饥肠副本是第一个，应该不需要下拉寻找。

### 日志记录

[2024-09-23.log](https://github.com/user-attachments/files/17091546/2024-09-23.log)

**Comment by moesnow** [comment]
当前日志缺乏有效信息，请将 `设置 → 程序 → 日志等级` 修改为 `详细` 后，重新复现一遍，再将日志内容上传。

**Comment by moesnow** [comment]
56051cc81cdec2d01106639242d79046bdeb0f9e
