### ISSUE TITLE
[Bug]: QWidget报错

### ISSUE THREAD

**Issue by Loshepherd** [moesnow/March7thAssistant#348]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.5.4

### 重现步骤

按照教程安装运行

<details>

<summary>安装步骤</summary>

#### 源码运行

git clone --recurse-submodules https://github.com/moesnow/March7thAssistant
cd March7thAssistant
pip install -r requirements.txt
python app.py

</details>

### 期望的结果是什么？

正常运行gui界面

### 实际的结果是什么？

报错QWidget: Must consturct a QApplication before a QWidget，程序自动退出。

<details>

<summary>报错界面</summary>

![屏幕截图 2024-10-01 014338](https://github.com/user-attachments/assets/67fe4fd6-6879-4ba3-a6b5-a025c9d26eca)

</details>

### 补充说明（可选）

手动编辑config.yaml，运行python main.py ，程序可正常运行

**Comment by Shotazt** [comment]
你这看起来好像用的是源码版啊

**Comment by moesnow** [comment]
Python 版本是什么？
建议直接下载打包后的版本 [March7thAssistant v2.5.4](https://github.com/moesnow/March7thAssistant/releases/tag/v2.5.4)

**Comment by Loshepherd** [comment]
> 你这看起来好像用的是源码版啊

是用的源码版本

**Comment by Loshepherd** [comment]
> Python 版本是什么？ 建议直接下载打包后的版本 [March7thAssistant v2.5.4](https://github.com/moesnow/March7thAssistant/releases/tag/v2.5.4)

多谢建议，将python从3.12降级到3.11可以正常运行了

建议在readme中加入“推荐使用python3.11运行”
