### ISSUE TITLE
[Bug]: 远程桌面多开，一个用户打完了会关闭其他用户进程

### ISSUE THREAD

**Issue by Twilight-Z** [moesnow/March7thAssistant#35]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.6.4

### 重现步骤

远程连接当前电脑其他用户桌面，双开或以上启动游戏和程序。
程序设置的是打完自动退出游戏。
结果退出了其他没打完的用户的游戏进程。

可能是程序根据进程名关闭游戏的，
导致一个打完了会退出其他用户的游戏进程。
如果第一个启动的第一个打完等按顺序打完可能才会关闭正确的游戏进程。

### 期望的结果是什么？

远程用户打完只会退出关闭当前用户的游戏进程。

### 实际的结果是什么？

一个用户打完了会退出其他用户游戏进程

### 补充说明（可选）

可能是程序根据进程名关闭游戏的，
导致一个打完了会退出其他用户的游戏进程。
如果第一个启动的第一个打完等按顺序打完可能才会关闭正确的游戏进程。

**Comment by wanli123a** [comment]
1.6.9  求更新这个问题。目前双开 换了路径 还是容易这样

**Comment by MusherM** [comment]
1.7.5 依然存在这个问题，一边提示成功关闭，但是那边的没退出，一边正常打着，已经被关掉了

**Comment by MusherM** [comment]
不知道程序是不是直接根据进程名kill掉进程了，能否通过点击游戏内退出按键的方式进行关闭，以规避这个问题

**Comment by MusherM** [comment]
@moesnow 不知道该如何贡献给这个项目？我目前有一些思路，有意尝试解决这个问题，我是该 fork 一份，修改完提交 merge 申请吗？

**Comment by moesnow** [comment]
> 我是该 fork 一份，修改完提交 merge 申请吗？

对。

> 不知道程序是不是直接根据进程名kill掉进程了，能否通过点击游戏内退出按键的方式进行关闭，以规避这个问题

现在的实现就是直接 kill 进程名，加一个判断程序进程当前桌面和游戏当前桌面应该能解决这个问题，我这边没有搭多桌面环境不方便调试。点游戏内按键偶尔会遇到热更新或掉线（某些无加速直连国际服玩家）之类的情况还挺麻烦的。

https://github.com/moesnow/March7thAssistant/blob/650462cb8d1c7e5ad614e86f8bae943563ae1c27/tasks/game/stop.py#L18-L30

**Comment by MusherM** [comment]
> > 我是该 fork 一份，修改完提交 merge 申请吗？
> 
> 对。
> 
> > 不知道程序是不是直接根据进程名kill掉进程了，能否通过点击游戏内退出按键的方式进行关闭，以规避这个问题
> 
> 现在的实现就是直接 kill 进程名，加一个判断程序进程当前桌面和游戏当前桌面应该能解决这个问题，我这边没有搭多桌面环境不方便调试。点游戏内按键偶尔会遇到热更新或掉线（某些无加速直连国际服玩家）之类的情况还挺麻烦的。
> 
> https://github.com/moesnow/March7thAssistant/blob/650462cb8d1c7e5ad614e86f8bae943563ae1c27/tasks/game/stop.py#L18-L30

已经提交PR，在我的电脑上测试通过

**Comment by moesnow** [comment]
fix https://github.com/moesnow/March7thAssistant/pull/113

**Comment by MusherM** [comment]
@moesnow 我的 PR 已经通过了，为什么我不在 contributers 里捏，这是我的第一次 PR，所以比较在意

**Comment by moesnow** [comment]
> @moesnow 我的 PR 已经通过了，为什么我不在 contributers 里捏，这是我的第一次 PR，所以比较在意

检查一下 GitHub 是否绑定了 commit 里相同的邮箱

<img width="514" alt="image" src="https://github.com/moesnow/March7thAssistant/assets/11678347/7863a688-e37a-4609-abcf-7bd33397f7dc">

**Comment by MusherM** [comment]
> > @moesnow 我的 PR 已经通过了，为什么我不在 contributers 里捏，这是我的第一次 PR，所以比较在意
> 
> 检查一下 GitHub 是否绑定了 commit 里相同的邮箱
> 
> <img alt="image" width="514" src="https://private-user-images.githubusercontent.com/11678347/299179392-7863a688-e37a-4609-abcf-7bd33397f7dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzc0NzgsIm5iZiI6MTcwNjA3NzE3OCwicGF0aCI6Ii8xMTY3ODM0Ny8yOTkxNzkzOTItNzg2M2E2ODgtZTM3YS00NjA5LWFiY2YtN2JkMzMzOTdmN2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3Yjg0YTQ0ZmNjZTViNDNiM2RlMDRlYTQ3ZDVjZjgzMWNiNTkyMzEyYzUwMzg4OTdmNzk3YmUzNzBjNzg0ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5SrHuL896UrqjzXhKb4nvM5kw_T69B_PsyR9q7wICf8">

哦原来是这样 感谢回复
