### ISSUE TITLE
[Feat]: 清体力选择副本能否加入多选机制，然后随机/按顺序选择副本进行刷取和清体力

### ISSUE THREAD

**Issue by XYZliang** [moesnow/March7thAssistant#351]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

如题，已经进入养老期了，体力都没啥用，平常开着小助手丢在另一台电脑上也不管他，偶尔上线做做活动和宇宙，太懒太佛系了
多余的体力，可以随机刷刷材料或者遗器就好了

**Comment by zzc-tongji** [comment]
+1，我也觉得这是个好想法。
