### ISSUE TITLE
[Bug]: 与飞霄战斗时如果被飞霄击败  三月七无法识别到战斗失败的画面

### ISSUE THREAD

**Issue by misaka10384** [moesnow/March7thAssistant#357]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.5.4

### 重现步骤

直接去找飞霄 被她淦碎就行
![Clip_2024-10-14_09-24-20](https://github.com/user-attachments/assets/3e3d40c6-a703-40da-886f-15726d304308)

### 期望的结果是什么？

发现被淦碎了  重新进入蘸豆

### 实际的结果是什么？

愣在原地

**Comment by moesnow** [comment]
#385
