### ISSUE TITLE
[Feat]: 將「每日實訓」製作成一個可以單一執行的功能

### ISSUE THREAD

**Issue by seriaati** [moesnow/March7thAssistant#36]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

# 功能描述
如同「鋤大地」、「模擬宇宙」、和「忘卻之庭」一樣，在主畫面新增一個能單獨執行「每日實訓」的按鈕。
點擊後執行「體力」和「日常」。
# 當前實現方式
至「設定」中將「鋤大地」、「模擬宇宙」、和「忘卻之庭」都關閉後回到主畫面點擊「完整運行」。
# 痛點
有時候想要執行包含鋤大地和模擬宇宙的完整運行，有時候又只想做每日實訓，這樣開開關關的總是很麻煩，希望能將每日實訓的功能獨立出來。

**Comment by Elegant1E** [comment]
是的，我也希望能增添这个功能

**Comment by moesnow** [comment]
v1.6.6 已支持
