### ISSUE TITLE
[Feat]:  bug 锄大地功能不开黄泉秘技点识别一路砍过去 撞墙延迟 打完选项自动关机勾选

### ISSUE THREAD

**Issue by qincenhua** [moesnow/March7thAssistant#360]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

锄大地 黄泉开秘技点一路砍过去打完勾选自动关机 撞墙延迟 进入剧情退不出来
![Screenshot_20241010_045622](https://github.com/user-attachments/assets/66fda1d6-59e0-4b60-a4db-582edbeeae7d)

**Comment by moesnow** [comment]
锄大地相关问题请反馈给对应项目 https://github.com/linruowuyin/Fhoe-Rail
