### ISSUE TITLE
[Bug]: 模拟宇宙卡在零食界面

### ISSUE THREAD

**Issue by Book-fall2wish** [moesnow/March7thAssistant#361]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.5.4

### 重现步骤

已更新模拟宇宙到最新版本。使用模拟宇宙功能，总会进入此界面
![1v3l0z2m et1](https://github.com/user-attachments/assets/f3b661bc-eba5-4d8c-8fe1-9e1eb2079077)
![k4234bol uoc](https://github.com/user-attachments/assets/eeb7cc27-6826-4f18-b37a-def0a3928a65)
退出此界面后可以看到每次都在使用4号位的阮梅，秘技点已空。下面截图中有两点秘技点，是我不小心吃了一个零食导致的。
![qoubflpd ybr](https://github.com/user-attachments/assets/15f1eb86-6dcf-46ef-847d-c1f8aec42f1b)

### 期望的结果是什么？

正常游完差分宇宙，进入下一关。
在模拟宇宙的设置中没有找到关于秘技点的设置，没有合成零食和使用零食的设置。

### 实际的结果是什么？

![k4234bol uoc](https://github.com/user-attachments/assets/eeb7cc27-6826-4f18-b37a-def0a3928a65)

### 日志记录

主体程序log(.\logs)
[2024-10-18.log](https://github.com/user-attachments/files/17427182/2024-10-18.log)
模拟宇宙log(.\3rdparty\Auto_Simulated_Universe\logs)
[log_2024-10-18-09-13.txt](https://github.com/user-attachments/files/17427186/log_2024-10-18-09-13.txt)

**Comment by moesnow** [comment]
模拟宇宙相关问题请反馈给对应项目 https://github.com/CHNZYX/Auto_Simulated_Universe
