### ISSUE TITLE
[Feat]: 登陆问题

### ISSUE THREAD

**Issue by qin-511** [moesnow/March7thAssistant#363]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

账号密码的登陆希望添加复制粘贴，直接复制粘贴账号密码减少登陆失败。特别是自动输入时的大小写切换和键盘不符合，没开大写，自动输入时是大写的形式

**Comment by moesnow** [comment]
https://github.com/moesnow/March7thAssistant/pull/227
当时讨论的结果是，剪贴板粘贴，账号密码容易被Ditto等软件记录到剪贴板历史
