### ISSUE TITLE
[Bug]: 【抽卡记录】功能无法正确识别灵砂及之后推出的五星角色

### ISSUE THREAD

**Issue by UnknownObject000** [moesnow/March7thAssistant#364]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.5.4

### 重现步骤

1. 打开游戏
2. 在游戏内查看几页抽卡记录
3. 点击【抽卡记录】菜单中的【更新数据】菜单
4. 等待数据更新完成

### 期望的结果是什么？

正常显示抽取到的五星角色信息

### 实际的结果是什么？

总抽数和累计未出5星数增加，复刻角色可以被正常识别但新的5星角色没有被识别出来。查看【导出数据】功能输出的JSON文件发现有部分项目的名称/星级为空字符串。例如：
```json
{
            "gacha_id": "2042",
            "gacha_type": "11",
            "item_id": "1223",
            "count": "1",
            "time": "2024-09-13 02:32:58",
            "name": "",
            "item_type": "",
            "rank_type": "",
            "id": "1726164600000366045"
}
```

### 日志记录

[2024-10-25.log](https://github.com/user-attachments/files/17522346/2024-10-25.log)
抽卡记录功能好像不会产生日志？

### 补充说明（可选）

通过观察JSON文件可得出，新角色返回的数据格式与原有角色应该是发生了变化。

**Comment by Shotazt** [comment]
从飞宵开始旧接口没有五星数据了,作者预计下一次更新会换API接口，所以请耐心等待

**Comment by moesnow** [comment]
[March7thAssistant v2.6.0](https://github.com/moesnow/March7thAssistant/releases/tag/v2.6.0)
升级后点击“更新完整数据”可以修复错误数据
