### ISSUE TITLE
[Feat]: 希望添加对新侵蚀隧洞（迷识之径）自动刷取的支持

### ISSUE THREAD

**Issue by UnknownCjer** [moesnow/March7thAssistant#365]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

![image](https://github.com/user-attachments/assets/eea3215d-501e-4e95-a3a9-691ca9130c43)

**Comment by moesnow** [comment]
4d7345fe802046ca5921f0fc6a6bd59afcf8d69d

**Comment by smallmj** [comment]
> 4d7345fe802046ca5921f0fc6a6bd59afcf8d69d

这个貌似没实装么？更新到最新版也没有这个

**Comment by moesnow** [comment]
> > 4d7345fe802046ca5921f0fc6a6bd59afcf8d69d
> 
> 这个貌似没实装么？更新到最新版也没有这个

没有，在等其他功能完成后再发新版
