### ISSUE TITLE
[Bug]: “弦音之形”选项不存在

### ISSUE THREAD

**Issue by LNGS-Horse** [moesnow/March7thAssistant#367]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.5.4

### 重现步骤

在清体力选项中不存在凝滞虚影“弦音之形”

### 期望的结果是什么？

如上

### 实际的结果是什么？

如上

### 补充说明（可选）

希望尽快填充

**Comment by moesnow** [comment]
[March7thAssistant v2.6.0](https://github.com/moesnow/March7thAssistant/releases/tag/v2.6.0)
