### ISSUE TITLE
[Advice]: 关于三月七小助手启动慢的解决办法

### ISSUE THREAD

**Issue by Shotazt** [moesnow/March7thAssistant#373]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

Windows自带的杀毒会导致三月七小助手每次启动时占用大量CPU，从而造成严重卡顿以至于打开速度极具减慢
![Screenshot_20241109-212024_ToDesk](https://github.com/user-attachments/assets/356be748-37f1-4392-940b-eec4b4afa1a9)
![Screenshot_20241109-213135_ToDesk](https://github.com/user-attachments/assets/b44a8c5a-e4cb-4213-92b0-4e44d3859450)
从而提出几个解决方案，如果有其他人提出类似的issue可以直接引用本描述（例如三月七启动慢或者打不开会挂在任务管理器中）
1.关闭微软杀毒
![8E)X 5E_Q09$0XKHQG6%TSC](https://github.com/user-attachments/assets/5beecfdc-d031-4300-90a8-69b29565343e)

2.在微软杀毒中添加三月七小助手的文件夹排除项
![$_EI__`)SQHB1LT2%5P_2UY](https://github.com/user-attachments/assets/63b8aa59-b239-49fc-898a-c34eb7412df4)

**Comment by Shotazt** [comment]
可以设置置顶或者加入wiki

**Comment by 123hi123** [comment]
你是windows甚麼版本的 我怎麼沒這個選項
![image](https://github.com/user-attachments/assets/f356413b-e897-4ade-bb45-42e09b18b9d0)
