### ISSUE TITLE
[Feat]: 希望能加入邮件推送功能

### ISSUE THREAD

**Issue by worldline233** [moesnow/March7thAssistant#391]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

希望能在虚构叙事和混沌回忆队伍配置中支持灵砂；希望能加入邮件推送功能

**Comment by worldline233** [comment]
希望能加入邮件推送功能，由user自己提供发送和接收邮箱

**Comment by moesnow** [comment]
[Q：添加自定义通知的方式](https://moesnow.github.io/March7thAssistant/#/assets/docs/FAQ?id=q%ef%bc%9a%e6%b7%bb%e5%8a%a0%e8%87%aa%e5%ae%9a%e4%b9%89%e9%80%9a%e7%9f%a5%e7%9a%84%e6%96%b9%e5%bc%8f)
A：图形界面内只支持启用Windows原生通知，需要其他通知请在 config.yaml 中开启。
