### ISSUE TITLE
[Feat]: 关于无法及时添加新角色的办法

### ISSUE THREAD

**Issue by yhzcake** [moesnow/March7thAssistant#394]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的 Issue 和 PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

是否可以添加一个让使用者自己添加新角色的办法?
例如在软件根目录加个角色文件夹,把角色头像图片命名为角色名就能加进去,用于混沌虚构临时使用

**Comment by moesnow** [comment]
[Q：逐光捡金缺少新角色？](https://moesnow.github.io/March7thAssistant/#/assets/docs/FAQ?id=q%ef%bc%9a%e7%bc%ba%e5%b0%91%e6%96%b0%e5%a2%9e%e5%8a%a0%e7%9a%84%e5%89%af%e6%9c%ac%ef%bc%9f%e9%80%90%e5%85%89%e6%8d%a1%e9%87%91%e7%bc%ba%e5%b0%91%e6%96%b0%e8%a7%92%e8%89%b2%ef%bc%9f)
A：在忘却之庭的界面，用小助手工具箱中的捕获截图功能，勾选角色头像，点击保存所选截图后，

放入 assets\images\share\character ，并修改 assets\config\character_names.json 文件。
