### ISSUE TITLE
[Bug]: 三月七无法识别任意界面下角色死亡提示

### ISSUE THREAD

**Issue by misaka10384** [moesnow/March7thAssistant#395]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.6.3

### 重现步骤

两个界面  
第一个
队伍里存在死亡的角色时 进入任意副本点击开始挑战  此时弹出任意角色死亡的界面
![image](https://github.com/user-attachments/assets/4e37c718-8e06-4823-acec-97ce1b35256b)

第二个
在任意战斗中 任意角色死亡后战斗胜利 选择再来一次 此时弹出任意角色死亡的界面
![816d5c7aa5ad6ee91e26559b4e6b5fde](https://github.com/user-attachments/assets/8d98dd7b-f4ab-4d8e-bebc-929cf7280109)

### 期望的结果是什么？

选择取消后退出关卡 然后找一个传送锚点恢复生命值后传送回任务目标继续战斗

### 实际的结果是什么？

由于三月七识别不到该页面 愣住

### 日志记录

![53057995d1cf158018dde30280238e06](https://github.com/user-attachments/assets/98139950-d9c4-4519-ad2f-ad3cebe04743)
![PixPin_2024-11-29_12-29-35](https://github.com/user-attachments/assets/b8183dac-7a44-4d9a-b8a2-ec87ba50be79)
[2024-11-29.log](https://github.com/user-attachments/files/17954366/2024-11-29.log)

**Comment by moesnow** [comment]
重复 #343
