### ISSUE TITLE
[Bug]: 疑似因新壁纸原因识别不到邮箱，导致完整运行中断

### ISSUE THREAD

**Issue by Loner-Knowledge** [moesnow/March7thAssistant#405]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.7.0

### 重现步骤

1. 手动把壁纸切换到“愿今夜无梦”
2. 开启完整运行
3. 等待到邮箱奖励领取阶段

### 期望的结果是什么？

正常点击邮箱，切换到邮箱界面，进行邮箱奖励的领取。

### 实际的结果是什么？

在进行到领取邮箱奖励时，识别到mail_reward.png，但是接下来mail.png达不到识别阈值，于是在手机菜单界面卡住。

### 日志记录

从2024-12-08 07:09:02,415开始
[2024-12-07.log](https://github.com/user-attachments/files/18050889/2024-12-07.log)

### 补充说明（可选）

识别的问题上，因为这个壁纸背景的原因，好巧不巧就在邮箱那一块不是背景纯色了，见下图。
![image](https://github.com/user-attachments/assets/e91495de-36a0-415f-a091-5b966c7e9973)

另外，之前确实有过类似问题（见#18，#19），也确实修复了，但当时修复的代码和现在的差别很大，并且用于切换壁纸的识别图片在现在的版本里也找不到，所以当时这个切换壁纸的功能现在是移除了吗？

当时修复的：
41b7d39074c19fc134623f1e1abbb01fecc5438f

**Comment by moesnow** [comment]
现在是采用透明背景的模板来匹配的，问题出在邮箱的阈值设置错误了。
