### ISSUE TITLE
[Bug]: 末日幻影快速挑战提示框无法识别并跳过

### ISSUE THREAD

**Issue by yhzcake** [moesnow/March7thAssistant#406]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

2.7.0

### 重现步骤

打末日幻影,第三关,弹出快捷挑战提示框,提示领取前两关奖励

### 期望的结果是什么？

自动识别并领取

### 实际的结果是什么？

无法识别窗口

### 日志记录

日志被覆盖丢失

### 补充说明（可选）

第一次自动运行报错后尝试再次运行,然后手动跳过了但是忘记截图了,并且还覆盖了第一次的日志

**Comment by Avabowler** [comment]
是指挑战完第三关后提示领取前两关奖励无法识别吗？

**Comment by Avabowler** [comment]
大概定位到问题了，我晚上回去添加下这部分逻辑。

**Comment by yhzcake** [comment]
> 是指挑战完第三关后提示领取前两关奖励无法识别吗？

对的对的，这还不太好复现，毕竟一期只能打一次
