### ISSUE TITLE
[Bug]: 遊戲打開地圖介面，但是無法識別出來，重複數次後跳出ERROR

### ISSUE THREAD

**Issue by kevin-xiaoyi** [moesnow/March7thAssistant#408]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2.7.0

### 重现步骤

![螢幕擷取畫面 2024-12-11 111428](https://github.com/user-attachments/assets/5f010cb5-60e8-466c-9f14-fc553d808244)

### 期望的结果是什么？

清體力

### 实际的结果是什么？

卡在地圖介面

**Comment by moesnow** [comment]
打开地图按键是M吗
