### ISSUE TITLE
[Bug]: 使用消耗品失败

### ISSUE THREAD

**Issue by bling-yshs** [moesnow/March7thAssistant#41]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v1.6.4

### 重现步骤

完整运行->使用消耗品失败

### 期望的结果是什么？

使用消耗品

### 实际的结果是什么？

使用消耗品失败

### 日志记录

[2023-11-13_20-05-38.log](https://github.com/moesnow/March7thAssistant/files/13334591/2023-11-13_20-05-38.log)

### 补充说明（可选）

不知道啥情况，总之我第一次运行的时候，他帮我自动合成了一个简易护具，然后打开背包筛选防御类消耗品，然后就尬住了...
![image](https://github.com/moesnow/March7thAssistant/assets/41812674/5c48600a-be23-41b7-a2a0-98c50706d0bb)

**Comment by moesnow** [comment]
看样子是筛选防御类消耗品后，缺少延迟，导致点击物品后未成功选中。

**Comment by bling-yshs** [comment]
> 看样子是筛选防御类消耗品后，缺少延迟，导致点击物品后未成功选中。

确实，鼠标停在那个简易护具上面，然后他就什么都不动了

**Comment by moesnow** [comment]
204f475541a65473a5aa764e0d20e33bc1a4500b
