### ISSUE TITLE
[Bug]: 在点击下载更新后程序直接闪退

### ISSUE THREAD

**Issue by LeberechtHan** [moesnow/March7thAssistant#415]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2024.12.12

### 重现步骤

无论是设置-检查更新还是打开软件后的更新提醒，只要点击下载键程序就直接闪退
![屏幕截图 2024-12-20 104542](https://github.com/user-attachments/assets/c131eff9-baca-44e8-85b3-e4773af7a2b4)

### 期望的结果是什么？

下载并安装更新

### 实际的结果是什么？

程序闪退

### 日志记录

日志没有表现这方面内容，因为没有启动运行

**Comment by LeberechtHan** [comment]
[2024-12-20.log](https://github.com/user-attachments/files/18205365/2024-12-20.log)

**Comment by moesnow** [comment]
有尝试手动打开 `March7th Updater.exe` 吗？也可以尝试手动覆盖更新
