### ISSUE TITLE
[Bug]: 突然无法更新

### ISSUE THREAD

**Issue by xiaoyi470** [moesnow/March7thAssistant#416]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v2024.12.12

### 重现步骤

今天突然更新，但是更新失败。
下载失败: Command '['E:\\迅雷下载\\自动狗粮\\March7thAssistant_v2.3.0_full\\assets\\binary\\aria2c.exe', '--max-connection-per-server=16', '--dir=E:\\迅雷下载\\自动狗粮\\March7thAssistant_v2.3.0_full\\temp', '--out=March7thAssistant_v2024.12.18_full.7z', 'https://github.kotori.top/https://github.com/moesnow/March7thAssistant/releases/download/v2024.12.18/March7thAssistant_v2024.12.18_full.7z']' returned non-zero exit status 1.

### 期望的结果是什么？

看看是否能处理

### 实际的结果是什么？

谢谢

**Comment by moesnow** [comment]
可以尝试代理软件或手动更新
