### ISSUE TITLE
[Bug]: 第八宇宙自动打时，会卡在角落

### ISSUE THREAD

**Issue by XGK666** [moesnow/March7thAssistant#45]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.66

### 重现步骤

自动打第八宇宙大概到6/13时，会有一个小角落，人物会卡在小角落，人物自动左右移动也会卡在角落
<img width="958" alt="屏幕截图 2023-11-17 195134" src="https://github.com/moesnow/March7thAssistant/assets/100862977/0cb73130-8444-42f7-9393-553b348b72fc">

### 期望的结果是什么？

不要卡在角落，可以从旁边台阶上去接着打怪

### 实际的结果是什么？

卡在角落，来回走动，但是上不了楼梯

### 日志记录

[2023-11-17_19-24-38.log](https://github.com/moesnow/March7thAssistant/files/13391311/2023-11-17_19-24-38.log)

**Comment by moesnow** [comment]
请反馈给模拟宇宙项目：https://github.com/CHNZYX/Auto_Simulated_Universe
