### ISSUE TITLE
[Bug]: 每日实训包含模拟宇宙时无法正常完成

### ISSUE THREAD

**Issue by bling-yshs** [moesnow/March7thAssistant#46]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v1.6.6

### 重现步骤

三月七助手->每日实训->遇到每日任务包含模拟宇宙->报错
![image](https://github.com/moesnow/March7thAssistant/assets/41812674/77b15681-edb9-422a-96a5-9559638f673a)

### 期望的结果是什么？

1

### 实际的结果是什么？

1

### 日志记录

[2023-11-18_13-35-41.log](https://github.com/moesnow/March7thAssistant/files/13399112/2023-11-18_13-35-41.log)

### 补充说明（可选）

提示模拟宇宙路径不存在，但是我发现本地确实是有那个文件的，就很奇怪，主程序目录是在 `C:\abys\软件\March7thAssistant_v1.6.4`
![image](https://github.com/moesnow/March7thAssistant/assets/41812674/5c84bca1-ee64-4bdb-9e26-eddc83c23f10)

**Comment by moesnow** [comment]
v1.6.5 版本开始新增了集成版模拟宇宙，且默认使用。
你截图中的目录内是源码版，正常情况是会下载一个集成版的。
解决方案：
1.设置-模拟宇宙 切换到源码模式
2.设置-模拟宇宙 点击更新

**Comment by bling-yshs** [comment]
> v1.6.5 版本开始新增了集成版模拟宇宙，且默认使用。 你截图中的目录内是源码版，正常情况是会下载一个集成版的。 解决方案 任选其一： 1.设置-模拟宇宙 切换到源码模式 2.设置-模拟宇宙 点击更新

根据解决方案解决了
