### ISSUE TITLE
[Feat]: 自动点击剧情功能

### ISSUE THREAD

**Issue by LavendaRaphael** [moesnow/March7thAssistant#51]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

希望添加自动点击剧情功能，因为剧情信息密度较低，自动点击剧情能够加速剧情任务，优化游戏体验，但是目前似乎没有发现有该功能

**Comment by wewieai** [comment]
真的很需要这个功能。

**Comment by akyra0721** [comment]
同求

**Comment by TheStarry001** [comment]
同求,很需要很需要
