### ISSUE TITLE
[Feat]:希望优化助战借用关于非简中语言的OCR识别 

### ISSUE THREAD

**Issue by ZM-Meribel** [moesnow/March7thAssistant#53]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

March7thAssistant 版本 （或 Commit Id）
1.6.6
经过5次重复测试。当我在三月七助手的清体力模块的支援功能选择“启用使用支援角色”，并指定以下好友时：['遊川ナナコ', '三月轮廻', '鸭鸭呀']
软件只能检测到第三位好友（当界面里存在时）。对于存在片假的好友1和存在繁体中文的好友2,五次测试中软件均未能识别。
希望本工程优化助战识别对于日文，繁体中文，符号（我还有一个颜文字的出生好友ID没测）的支持

**Comment by moesnow** [comment]
尝试使用 UID 代替用户名
[March7thAssistant v1.7.7.3](https://github.com/moesnow/March7thAssistant/releases/tag/v1.7.7.3)
