### ISSUE TITLE
[Feat]: 建议增加体力换沉浸器的功能

### ISSUE THREAD

**Issue by lostinforest** [moesnow/March7thAssistant#55]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

建议增加一个体力兑换沉浸器的功能，比如可以设置每次清体力之前兑换 x 粒沉浸器这样，在需要刷位面遗器的时候就可以预先把体力存下来等有空的时候单独刷宇宙了 >.<
谢谢！！

**Comment by moesnow** [comment]
52a9907dcccd37a9d9a15724af267f84981e21cd

**Comment by lostinforest** [comment]
感谢作者这么快就加上了！！！
