### ISSUE TITLE
[Bug]: 完整運行失敗

### ISSUE THREAD

**Issue by zihuanfeng520** [moesnow/March7thAssistant#58]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.6.8

### 重现步骤

更新完1.6.8後，使用完整運行，cmd跳出[啟動 `"C:\Users\Huanfeng\Desktop\March7thAssistant_v1.5.1\March7th Assistant.exe" main' 時發生錯誤 2147942402 (0x80070002)]

### 期望的结果是什么？

[啟動 `"C:\Users\Huanfeng\Desktop\March7thAssistant_v1.5.1\March7th Assistant.exe" main' 時發生錯誤 2147942402 (0x80070002)]

### 实际的结果是什么？

[啟動 `"C:\Users\Huanfeng\Desktop\March7thAssistant_v1.5.1\March7th Assistant.exe" main' 時發生錯誤 2147942402 (0x80070002)]

### 日志记录

[啟動 `"C:\Users\Huanfeng\Desktop\March7thAssistant_v1.5.1\March7th Assistant.exe" main' 時發生錯誤 2147942402 (0x80070002)]

### 补充说明（可选）

此版本前並無問題

**Comment by moesnow** [comment]
尝试重新下载 [March7thAssistant_v1.6.8_full.zip](https://github.com/moesnow/March7thAssistant/releases/download/v1.6.8/March7thAssistant_v1.6.8_full.zip)

**Comment by zihuanfeng520** [comment]
重新下載有用 感謝，因為之前更新都能直接用 沒考慮到可能有衝突
