### ISSUE TITLE
[Bug]: 无限重复打回忆一

### ISSUE THREAD

**Issue by yukiryo** [moesnow/March7thAssistant#59]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.6.8

### 重现步骤

开启通过回忆一完成任务

### 期望的结果是什么？

打一次回忆一

### 实际的结果是什么？

无限重复

### 补充说明（可选）

![image](https://github.com/moesnow/March7thAssistant/assets/58250223/3653c57f-51d0-4360-a138-771be02750fa)

**Comment by moesnow** [comment]
如果有“利用弱点进入战斗并获胜3次”的实训连着打3次是正常的
