### ISSUE TITLE
[Bug]: 更新1.4.1和群文件里锄大地py文件后，在锄大地的时候1号位的驭空会自动使用秘技，秘技点用光以后自动打开秘技药界面，然后不吃药卡住在那了

### ISSUE THREAD

**Issue by f59375543** [moesnow/March7thAssistant#6]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.4.1

### 重现步骤

更新1.4.1和群文件里锄大地py文件后，在锄大地的时候1号位的驭空会自动使用秘技，秘技点用光以后自动打开秘技药界面，然后不吃药卡住在那了

### 期望的结果是什么？

不自动使用秘技，或者使用秘技后自动吃药

### 实际的结果是什么？

无法吃药，卡在那一动不动很久没有反应

### 日志记录

[2023-09-23_09-42-50.log](https://github.com/moesnow/March7thAssistant/files/12705896/2023-09-23_09-42-50.log)

**Comment by moesnow** [comment]
请检查是否修改过默认按键，F是交互，R是使用秘技

**Comment by f59375543** [comment]
> 请检查是否修改过默认按键，F是交互，R是使用秘技

啊，我突然发现原因了，是否是因为群文件的py文件改了R？
![20230923161230](https://github.com/moesnow/March7thAssistant/assets/43315911/882afd8e-8b1d-4a04-a5a9-db4092e25a3f)

**Comment by moesnow** [comment]
> > 请检查是否修改过默认按键，F是交互，R是使用秘技
> 
> 啊，我突然发现原因了，是否是因为群文件的py文件改了R？ ![20230923161230](https://user-images.githubusercontent.com/43315911/270095801-882afd8e-8b1d-4a04-a5a9-db4092e25a3f.png)

这个文件是给“修改R为交互按键”的用户使用的，正常F交互不需要修改

**Comment by f59375543** [comment]
> > > 请检查是否修改过默认按键，F是交互，R是使用秘技
> > 
> > 
> > 啊，我突然发现原因了，是否是因为群文件的py文件改了R？ ![20230923161230](https://user-images.githubusercontent.com/43315911/270095801-882afd8e-8b1d-4a04-a5a9-db4092e25a3f.png)
> 
> 这个文件是给“修改R为交互按键”的用户使用的，正常F交互不需要修改



我懂了，现在替换回旧py，谢谢
