### ISSUE TITLE
[Bug]: 忘却之庭混沌回忆，不会自动进入下一关

### ISSUE THREAD

**Issue by bling-yshs** [moesnow/March7thAssistant#62]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v1.6.8

### 重现步骤

主页->忘却之庭->自动开始打->打完在主页发呆，如图：
![image](https://github.com/moesnow/March7thAssistant/assets/41812674/ed474649-9a98-4e10-8264-8a509a023ad3)

### 期望的结果是什么？

自动进入下一关

### 实际的结果是什么？

发呆

### 日志记录

[2023-11-27_10-47-48.log](https://github.com/moesnow/March7thAssistant/files/13469278/2023-11-27_10-47-48.log)

**Comment by moesnow** [comment]
[v1.6.9](https://github.com/moesnow/March7thAssistant/releases/tag/v1.6.9)
