### ISSUE TITLE
[Bug]: 在三月七助手中点击模拟宇宙，配置是读取Auto_Simulated_Universe的吗？

### ISSUE THREAD

**Issue by Canda15** [moesnow/March7thAssistant#67]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v1.6.9

### 重现步骤

见下文

### 期望的结果是什么？

见下文

### 实际的结果是什么？

我在原版运行弹出Auto_Simulated_Universe的GUI后更改了难度和勾选了快速通关（即只打每层最后一个怪）。保存后。通过三月七首页点击模拟宇宙运行，难度生效了，但是快速通关没有生效，仍然打第一个怪。之后尝试原版运行后，原版没有出现这种情况。

**Comment by moesnow** [comment]
通过小助手启动，目前无法配置“速通”等模式
