### ISSUE TITLE
[Feat]: 每日任务，队伍练度不够 队伍全部死亡 不会进行下一步 

### ISSUE THREAD

**Issue by ddd-zero** [moesnow/March7thAssistant#71]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

做每日任务的时候，如果4个角色全死完了。不会点退出或者重试。上错阵容的时候发现的。希望重试或者推送报警。或者自动切换队伍重新尝试，如果前几个阵容都无法完成，再推送报警。或者直接跳过这个任务也行

**Comment by moesnow** [comment]
建议配一个强力队伍，放在5/6等不常用的位置，然后设置修改使用这个队伍。
