### ISSUE TITLE
[Feat]: 关于锄大地功能的改进建议

### ISSUE THREAD

**Issue by zmy1828** [moesnow/March7thAssistant#73]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

希望锄大地路线中能增加对地图中可破坏物品的记录，同时在长距离跑图中增加自动使用驭空/饮月秘技的功能，提高锄大地总产出和效率。当然目前锄大地功能已经很强大了，只是一点小建议。

**Comment by YS-AG** [comment]
希望锄大地和模拟宇宙一样，当挑战失败时，可以自动点击空白区域，以继续锄大地。

**Comment by Canda15** [comment]
提错地方了。锄大地是调用的别的项目。
https://github.com/linruowuyin/Fhoe-Rail/issues
