### ISSUE TITLE
[Feat]: 忘却之庭未支持银枝，寒鸦等新角色

### ISSUE THREAD

**Issue by LoSiTeE** [moesnow/March7thAssistant#76]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

看了角色文件夹，没有找到银枝，寒鸦。麻烦做一下支持，谢谢。

**Comment by TigerSchnee** [comment]
可以先自己截图起个名字扔角色文件夹里

**Comment by moesnow** [comment]
缺少银枝的头像，方便的话麻烦在忘却之庭的界面，用小助手设置中的捕获截图功能，点击保存完整图片后，用未压缩的方式传上来，比如压缩包。

**Comment by TigerSchnee** [comment]
> 缺少银枝的头像，方便的话麻烦在忘却之庭的界面，用小助手设置中的捕获截图功能，点击保存完整图片后，用未压缩的方式传上来，比如压缩包。

我没有银枝，但可以贡献一下阮·梅
[RuanMei.zip](https://github.com/moesnow/March7thAssistant/files/13785998/RuanMei.zip)

**Comment by 0frostmourne0** [comment]
银枝
[Argenti.zip](https://github.com/moesnow/March7thAssistant/files/13797510/Argenti.zip)
