### ISSUE TITLE
不能开始运行脚本

### ISSUE THREAD

**Issue by mengqi1230** [moesnow/March7thAssistant#78]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

w11 

### 重现步骤

.

### 期望的结果是什么？

这个怎么弄

### 实际的结果是什么？

.

### 日志记录

[出现错误 2147942402 (0x80070002) (启动“"D:\360安全浏览器下载\2\新建文件夹\March7thAssistant_v1.6.9\March7th Assistant.exe" main”时)]

### 补充说明（可选）

.

**Comment by mengqi1230** [comment]
![R51BX$N33@@DY LDJ2NEY9B](https://github.com/moesnow/March7thAssistant/assets/154420428/2d96a833-a0d4-419c-bf10-2309dbaf2345)

**Comment by moesnow** [comment]
https://github.com/moesnow/March7thAssistant/discussions/79
