### ISSUE TITLE
[Bug]: [出现错误 2147942402 (0x80070002) (启动“"D:\GameTool\March7thAssistant_v1.6.6\March7th Assistant.exe" main”时)]

### ISSUE THREAD

**Issue by ymdm2** [moesnow/March7thAssistant#82]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

v1.6.9

### 重现步骤

昨天还在正常使用，今天启动直接报错，执行每项任务都会报同样的错误。
[出现错误 2147942402 (0x80070002) (启动“"D:\GameTool\March7thAssistant_v1.6.6\March7th Assistant.exe" main”时)]
[出现错误 2147942402 (0x80070002) (启动“"D:\GameTool\March7thAssistant_v1.6.6\March7th Assistant.exe" daily”时)]
...etc

### 期望的结果是什么？

正常使用。除此之外，希望增加修改按键的功能，默认地图按键应该是x，软件地图按键是m，为了使用软件修改了对应按键，但还是希望增加该功能

### 实际的结果是什么？

无法启动，会报错

**Comment by moesnow** [comment]
重复问题 https://github.com/moesnow/March7thAssistant/discussions/79
