### ISSUE TITLE
[Bug]: 无法完成每日实训

### ISSUE THREAD

**Issue by Diorite9248** [moesnow/March7thAssistant#83]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.6.9

### 重现步骤

打开“完整运行”或单独点击“每日实训”

### 期望的结果是什么？

进行每日实训

### 实际的结果是什么？

点开“侵蚀隧洞”——传送至“霜风之径”——停住不动
![bug](https://github.com/moesnow/March7thAssistant/assets/154493953/2d7f2170-b6c3-457d-857d-f06fb49c8229)

### 日志记录

[2023-12-28_08-41-03.log](https://github.com/moesnow/March7thAssistant/files/13782353/2023-12-28_08-41-03.log)

### 补充说明（可选）

似乎是1.6版本更新后才有的bug

**Comment by Robotmaid** [comment]
一样的，主要原因是忘却之庭换位置了

**Comment by moesnow** [comment]
[March7thAssistant v1.7.0](https://github.com/moesnow/March7thAssistant/releases/tag/v1.7.0)
