### ISSUE TITLE
[Bug]: 更新后无法锄大地

### ISSUE THREAD

**Issue by ssssshql** [moesnow/March7thAssistant#84]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.7.0

### 重现步骤

1.6升级为1.7.0后，无法锄大地。原版运行没问题。
![image](https://github.com/moesnow/March7thAssistant/assets/53895670/17846c3a-71e1-45bc-b801-90b22849f00b)

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

按回车键关闭窗口

**Comment by SobMintCandy** [comment]
也无法运行模拟宇宙
