### ISSUE TITLE
[Bug]: “体力”和“锄大地”界面中“队伍编号”只有3-7了，没有1和2

### ISSUE THREAD

**Issue by Diorite9248** [moesnow/March7thAssistant#88]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.7.1

### 重现步骤

打开三月七小助手

### 期望的结果是什么？

队伍有1和2

### 实际的结果是什么？

只有3-7
![f828ea3ff30e1ddd6a33a80885d17c5](https://github.com/moesnow/March7thAssistant/assets/154493953/a15cb774-fa69-41a4-9bad-2b39f134ff36)
![566b7397338451a41e20b7075eec48f](https://github.com/moesnow/March7thAssistant/assets/154493953/1f38a10e-0a09-4c12-8b15-2ec33c9a2af3)

**Comment by moesnow** [comment]
图形界面是故意这样改的，更新后队伍1和2有概率会选不到。
