### ISSUE TITLE
[Feat]: 

### ISSUE THREAD

**Issue by zihuanfeng520** [moesnow/March7thAssistant#9]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 以及 [Pull Request](https://github.com/moesnow/March7thAssistant/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

在設定中已經有使用可以更改使用秘技的按鍵了，能再加一個更改使用交互鍵的按鍵嗎？因為我個人習慣用e，目前只能暫時先改成f，在此先謝過大佬們的無私付出了！

**Comment by moesnow** [comment]
目前 `March7thAssistant` 没有用到交互键哦，修改秘技按键也只有忘却之庭生效。

模拟宇宙 `Auto_Simulated_Universe` 的按键可以在 `info_example.yml` 里面修改。

锄大地 `Fhoe-Rail` 的 `utils` 目录中有一个名称包含 `改按键` 的 `py` 文件是 `E` 和 `F` 互换的

**Comment by zihuanfeng520** [comment]
了解 因為之前別人的鋤地助手在太空站有用到交互鍵開門，想說這邊連密技都能更換按鍵，那交互應該也可以，沒仔細坐在電腦前看是否有使用到交互鍵，謝謝解惑!
