### ISSUE TITLE
[Bug]: 体力识别出错

### ISSUE THREAD

**Issue by yhzcake** [moesnow/March7thAssistant#90]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.7.1

### 重现步骤

执行清体力

### 期望的结果是什么？

正确识别体力数值

### 实际的结果是什么？

![image](https://github.com/moesnow/March7thAssistant/assets/80627671/1f3d4c08-32d4-4cde-a3a3-b1a9d56f2581)
504240识别的没问题,但是得到的结果是-1,实际应为504

### 日志记录

[2023-12-29_13-18-35.log](https://github.com/moesnow/March7thAssistant/files/13791137/2023-12-29_13-18-35.log)

**Comment by moesnow** [comment]
正常来说体力中间的`/`也是能识别出来的，可以手动消耗一点体力后再重试

**Comment by yhzcake** [comment]
我猜到大概是体力太多了识别有问题,不过感觉可以判断字符串纯数字从后面删240当当前开拓力,但是不知道会不会还有别的bug
还有就是,配队按键能设置了吗,这个默认t平时跑活动有点难受

**Comment by moesnow** [comment]
> 我猜到大概是体力太多了识别有问题,不过感觉可以判断字符串纯数字从后面删240当当前开拓力,但是不知道会不会还有别的bug 还有就是,配队按键能设置了吗,这个默认t平时跑活动有点难受

配队很早以前就改成从手机点图标进入了

**Comment by yhzcake** [comment]
我没注意..
上次我问你说加改按键,没想到直接改手机进了
我还一直盯着改按键那里看呢
