### ISSUE TITLE
[Bug]: 传送忘却之庭错误

### ISSUE THREAD

**Issue by 0frostmourne0** [moesnow/March7thAssistant#91]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

1.71  28dca5c

### 重现步骤

忘却之庭通过F4传送时，程序会点击到“信用点”图标(图中红框处)，然后卡在信用点说明界面，多次传送失败后跳过执行忘却之庭。
猜测是传送按钮坐标错误导致。
![20231229191116](https://github.com/moesnow/March7thAssistant/assets/23077424/852e2099-98cf-4651-9915-704c003eda15)

此外，运行过程中偶尔会自行取消自动战斗，必须手动点击自动才能继续战斗。

### 期望的结果是什么？

正确传送到忘却之庭

### 实际的结果是什么？

卡在信用点介绍界面，无法正确传送。

### 补充说明（可选）

**Comment by moesnow** [comment]
无法复现问题，需要提供录屏。坐标是通过识别`传送`文字的位置再点击的，不是固定的。

**Comment by 0frostmourne0** [comment]
视频尺寸剪裁了一部分。游戏分辨率是1920*1080，其他功能运行都正常。
https://github.com/moesnow/March7thAssistant/assets/23077424/70ed10a3-ff9f-40f5-9f77-81f6d12cbde8

**Comment by moesnow** [comment]
已修复，尝试一下测试版 https://github.com/moesnow/March7thAssistant/actions/runs/7358088789

**Comment by moesnow** [comment]
自行取消自动战斗的问题在等米哈游修复一个UI上的Bug

**Comment by seriaati** [comment]
> 自行取消自动战斗的问题在等米哈游修复一个UI上的Bug

能否新增一個設置讓玩家手動關閉「自動調整自動戰鬥功能」的功能？
由於其他設置中「沿用自動戰鬥設置」的存在，其實沒有「自動調整自動戰鬥功能」的必要。

**Comment by 0frostmourne0** [comment]
感谢大佬，经测试 [4507c8a](https://github.com/moesnow/March7thAssistant/commit/4507c8a3d9d889bd8925ab9bf2131cf14fca66f9) 已经修复传送问题。
