### ISSUE TITLE
[Docs]: 文檔中的「后台运行」設置教學中提到的檔案可能含有病毒

### ISSUE THREAD

**Issue by seriaati** [moesnow/March7thAssistant#99]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/moesnow/March7thAssistant/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭/锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### March7thAssistant 版本 （或 Commit Id）

_

### 重现步骤

在文檔中的 [後台運行（遠程本地多用戶桌面）](https://moesnow.github.io/March7thAssistant/#/assets/docs/Tutorial?id=%e5%90%8e%e5%8f%b0%e8%bf%90%e8%a1%8c%ef%bc%88%e8%bf%9c%e7%a8%8b%e6%9c%ac%e5%9c%b0%e5%a4%9a%e7%94%a8%e6%88%b7%e6%a1%8c%e9%9d%a2%ef%bc%89) 篇章提到關於 [详细教程 by_Rin](https://www.bilibili.com/read/cv24286313/)（推荐），其中，點擊下載後下載的 zip 檔以及解壓縮後的可執行檔皆被 virustotal 偵測為含有木馬病毒程式。另外，在嘗試下載時 Windows Defender 也會嘗試阻止並兩次警告使用者此檔案可能有危險。
![image](https://github.com/moesnow/March7thAssistant/assets/61446626/8c252fa2-6c4b-40e9-92ae-5551ab1e2023)

在強制允許下載後，上傳至 Virustotal 進行病毒檢查後得到的報告連結：
[zip 本身](https://www.virustotal.com/gui/file/4fe795c586599aeb6241ac8010fb2dce96a096f12a510e82cf6c84ee3453fa5e)

解壓縮後：
[exe 執行檔](https://www.virustotal.com/gui/file/d73c0af4652484e1a613136af01bdc48a750a9cfb65d77560534b4dbb8cecb75)
[SimpleRemote.exe](https://www.virustotal.com/gui/file/daca8483024fb1667afce8f54ad60cd2a0f3c70f8d950bab28077df4afcacb85)
[SuperRDP2.exe](https://www.virustotal.com/gui/file/f5f8aa30713a92f9be7e1980de67790feca16689245858b0464284872bcd9f56)
[SuperRDP.dll](https://www.virustotal.com/gui/file/09c912353f07773e07881322b6514c69396759bfaa57169284ed22c12cb52523)

其他例如圖片檔，PDF，及 reg 檔案都是安全的。
可以看到幾乎所有報告中都有超過半數的 security vendor 都認為檔案是可疑的，並且帶有木馬病毒的標籤。
我認為應當先下架文檔中這些檔案的下載來源，如果可以的話，嘗試追朔這些檔案的來源，並阻止病毒檔案繼續傳播。

### 期望的结果是什么？

_

### 实际的结果是什么？

_

**Comment by moesnow** [comment]
https://github.com/anhkgg/SuperRDP

**Comment by seriaati** [comment]
這是什麼意思？

**Comment by moesnow** [comment]
SuperRDP2项目的开源地址，杀毒软件误报是很常见的。
